### ISSUE TITLE
Jibir record/streaming button disappeared following latest update from unstable channel

### ISSUE THREAD

**Issue by zl1775** [jitsi/jibri#124]
Hi,

The issue is exactly as stated in the title. Everything with regard to jibri was working fine before the latest update. The updates were listed as following:

Get:1 https://download.jitsi.org unstable/ jitsi-meet 1.0.3126-1 [2,726 B]
Get:2 https://download.jitsi.org unstable/ jitsi-meet-web 1.0.2860-1 [6,321 kB]
Get:3 https://download.jitsi.org unstable/ jitsi-meet-web-config 1.0.2860-1 [11.6 kB]
Get:4 https://download.jitsi.org unstable/ jitsi-meet-prosody 1.0.2860-1 [5,776 B]

All the components are still running fine after the update: jibri, jitsi-video-bridge, prosody. I can start video conferences but jibri's functionality is nowhere to be found within the usual "settings" menu.

I honestly don't know what log files to provide here. Let me know if you guys know of a solution.

**Comment by bbaldino** [comment]
a change was recently pushed to jitsi-meet that changed the configuration values to enable recording/live streaming.  i haven't updated the jibri readme yet.  you must not set `fileRecordingsEnabled` ([here](https://github.com/jitsi/jitsi-meet/blob/master/config.js#L171)) and/or `liveStreamingEnabled` ([here](https://github.com/jitsi/jitsi-meet/blob/master/config.js#L171)) to enable them, as well as having them present in interface_config in the toolbar button array ([here](https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js#L47)).  check that and see if it fixes things.

**Comment by zl1775** [comment]
Great! That worked!
