### ISSUE TITLE
No "Start Live Stream" option and cannot install module snd-aloop

### ISSUE THREAD

**Issue by tansaku** [jitsi/jibri#133]
I've followed the install instructions https://github.com/jitsi/jibri#installing-jibri on xenial:

```
sam@AVJitsyServer:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

and I have two problems:

1) the "Start Live Stream" option does not show up
2) I was unable to install the snd-aloop module

I was hoping that adding the following to the jitsi config:

```
    // Recording

    // Whether to enable recording or not.
    enableRecording: true,

    // Type for recording: one of jibri or jirecon.
    recordingType: 'jibri',

    // Misc
    hiddenDomain: 'recorder.www.jitsi.agileventures.org',
```

would at least allow me to see the "Start Live Stream" button in our jitsi's but not so far ... 

Other changes to the config file such as disabling screenshare have an immediate effect when the jitsi interface is reloaded, but not `enableRecording` ...

I did ultimately manage to complete every other part of the jibri set up with the exception of installing the snd-aloop module:

```
sam@AVJitsyServer:~$ sudo apt-get install linux-image-extra-virtual
... successful install
sam@AVJitsyServer:~$ modprobe snd-aloop
modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/4.13.0-1011-azure
```

I found a [post](https://askubuntu.com/a/896004/611309) that suggested installing linux-generic, but that didn't help either:

```
sam@AVJitsyServer:~$ sudo apt install linux-generic
... successful install
sam@AVJitsyServer:~$ modinfo snd-aloop
modinfo: ERROR: Module snd-aloop not found.
```

I also reviewed the community mailing lists, but while I found lots of posts on problems setting up jibri. e.g. https://community.jitsi.org/t/jitsi-users-jibri/13827/5, I didn't find any for these two particular ones of the "start live stream" button not showing up at all, and the inability to install snd-aloop.

Here's our current jibri config:

https://gist.github.com/tansaku/7630dfc7bbcdd38da5dd498a52c76b9d

Here's a tail of the latest jibri logs:

https://gist.github.com/tansaku/90a8884b88160c30f0fe9ce29c9e98b8

I'm very happy to provide other logs and configs if that will help.
Many thanks in advance

**Comment by bbaldino** [comment]
The Jibri readme is out of date unfortunately (I just created a PR [here](https://github.com/jitsi/jibri/pull/134) to update it).  You can check the updated instructions there.

As for the snd-aloop issue, @aaronkvanmeerten might have some ideas, perhaps on your version it's in another package?

**Comment by aaronkvanmeerten** [comment]
For many kernels, the snd-aloop is in the -extra package, like: linux-image-extra-virtual

**Comment by bbaldino** [comment]
> For many kernels, the snd-aloop is in the -extra package, like: linux-image-extra-virtual

@aaronkvanmeerten it looks like this is the one he tried.  maybe it's the location it's searching for the modules?  `/lib/modules/4.13.0-1011-azure` seems surprising.

**Comment by aaronkvanmeerten** [comment]
Yes it may be that if he's still on the azure kernel that it hasn't switched to generic yet.  It may be necessary to remove the old kernel and reboot in order for ubuntu to switch over to the generic kernel

Here's the output of a kernel of a recent jibri in service for meet.jit.si
$ uname -a
Linux all-jibri-12266.jibri.jitsi.net 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sesangsokuro** [comment]
Linux jitsi.webzook.net 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
but in /lib/modules/, only 4.4.0-**131**-generic

how to handle it?

**Comment by kevin-og** [comment]
@sesangsokuro works under 4.4.0-116

**Comment by mrmookie** [comment]
I'm using Google Cloud instances.. the package needed for snd_aloop is '**linux-modules-extra-gcp**'

**Comment by frankodoom** [comment]
@tansaku did you solve this i have the same problem using an Azure VM

**Comment by mrmookie** [comment]
That would probably be the package: linux-modules-extra-azure

**Comment by frankodoom** [comment]
I fixed this removed the azure ubuntu conical special kernel with the -azure and I have it loaded nicely

**Comment by Soumojit28** [comment]
> I fixed this removed the azure ubuntu conical special kernel and loaded a more compatible kernel via grub. works. now :-)

can you tell me the instructions to do that?

**Comment by frankodoom** [comment]
> > I fixed this removed the azure ubuntu conical special kernel and loaded a more compatible kernel via grub. works. now :-)
> 
> can you tell me the instructions to do that?

https://www.neowin.net/news/canonical--microsoft-make-azure-tailored-linux-kernel/ 

Delete the kernel and in grub switch, to the new kernel you want to load 
https://unix.stackexchange.com/questions/198003/set-default-kernel-in-grub

**Comment by k3tman** [comment]
> I'm using Google Cloud instance.. Ubuntu 18.04.. the package needed for snd_aloop is '**linux-modules-extra-gcp**'

Thank you! This killed a lot of my time until I came across your post. thanks

**Comment by kavirajan2** [comment]
Jibri on AWS and getting the below issue.

> org.jitsi.jibri.capture.ffmpeg.FfmpegCapturer.onFfmpegProcessUpdate() Ffmpeg quit abruptly. Last output line: plug:bsnoop: Input/output error

**Solution:** changing and updating the kernel boot settings from Linux 4.4.0-xxxx-aws to Linux 4.4.0-xxxx-generic and restarting the instance.

I have fixed by the following steps:

> $ grep -A200 submenu  /boot/grub/grub.cfg |grep menuentry

**Output:**
```
submenu 'Advanced options for Ubuntu' $menuentry_id_option 'gnulinux-advanced-e6dc6474-8016-46c6-8ab0-0a871bae4cd1' {
	menuentry 'Ubuntu, with Linux 4.4.0-1107-aws' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.4.0-1107-aws-advanced-e6dc6474-8016-46c6-8ab0-0a871bae4cd1' {
	menuentry 'Ubuntu, with Linux 4.4.0-1107-aws (recovery mode)' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.4.0-1107-aws-recovery-e6dc6474-8016-46c6-8ab0-0a871bae4cd1' {
	menuentry 'Ubuntu, with Linux 4.4.0-1106-aws' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.4.0-1106-aws-advanced-e6dc6474-8016-46c6-8ab0-0a871bae4cd1' {
	menuentry 'Ubuntu, with Linux 4.4.0-1106-aws (recovery mode)' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.4.0-1106-aws-recovery-e6dc6474-8016-46c6-8ab0-0a871bae4cd1' {
	menuentry 'Ubuntu, with Linux 4.4.0-1105-aws' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.4.0-1105-aws-advanced-e6dc6474-8016-46c6-8ab0-0a871bae4cd1' {
	menuentry 'Ubuntu, with Linux 4.4.0-1105-aws (recovery mode)' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.4.0-1105-aws-recovery-e6dc6474-8016-46c6-8ab0-0a871bae4cd1' {
	menuentry 'Ubuntu, with Linux 4.4.0-179-generic' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.4.0-179-generic-advanced-e6dc6474-8016-46c6-8ab0-0a871bae4cd1' {
	menuentry 'Ubuntu, with Linux 4.4.0-179-generic (recovery mode)' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.4.0-179-generic-recovery-e6dc6474-8016-46c6-8ab0-0a871bae4cd1' {

```
 menu entry id for Advanced options for Ubuntu is gnulinux-advanced-e6dc6474-8016-46c6-8ab0-0a871bae4cd1
menu entry for Ubuntu, with Linux 4.4.0-179-generic is gnulinux-4.4.0-179-generic-advanced-e6dc6474-8016-46c6-8ab0-0a871bae4cd1

**Edit Grub** and replace GRUB_DEFAULT with above value

> $ nano /etc/default/grub

```
GRUB_DEFAULT="gnulinux-advanced-e6dc6474-8016-46c6-8ab0-0a871bae4cd1>gnulinux-4.4.0-179-generic-advanced-e6dc6474-8016-46c6-8ab0-0a871bae4cd1"
GRUB_HIDDEN_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0"
GRUB_CMDLINE_LINUX=""

```
**Update and Reboot**

> $ sudo update-grub
> $ sudo reboot

After reboot you can test it with uname -a which should give 4.4.0-179-generic

> $ uname -a

Linux 4.4.0-179-generic 

After this modprobe snd-aloop should work fine.

**Comment by lokeshdwivedi** [comment]
Its also work for azure ubuntu 18 thanks

**Comment by dimasanwaraziz** [comment]
> I'm using Google Cloud instance.. Ubuntu 18.04.. the package needed for snd_aloop is '**linux-modules-extra-gcp**'

Thank's, it's work for me

**Comment by TsaiRongFu** [comment]
> 我正在使用 Google Cloud 實例.. Ubuntu 18.04.. snd_aloop 所需的軟體包是 ' **linux-modules-extra-gcp** '

gooooooooooooooooooood
