### ISSUE TITLE
how to make .deb 

### ISSUE THREAD

**Issue by supun19** [jitsi/jibri#140]
I want to build .deb file from jibri. could someone help me?

**Comment by damencho** [comment]
```
resources/jenkins/build.sh
resources/jenkins/release.sh Major
```
You need to fill some variables that are needed by the scripts, check the scripts and fill them.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
