### ISSUE TITLE
how can i  integrate SIP video with jibri ?

### ISSUE THREAD

**Issue by fuqiangleon** [jitsi/jibri#142]
Hi,sir
I have checked all documents and find a way to intergrate SIP with jigasi component.but actually we need to integrate SIP audio and video to jitsi conference. 

I have found the document : sip_gateway.md  ,but its very short, so how can i config jibri to support SIP ?

Anybody knows that ?  hope get your help ~
Have a nice day .

By the way ,jitsi is very good project ,thanks for your nice work.

**Comment by bbaldino** [comment]
Jibri joins different MUCs on Jicofo to advertise capabilities.  We have one MUC for recording and another for SIP gateway, so you'll need to set the name of the SIP MUC on Jibri so that it will join that and Jicofo will see it.  Jicofo needs some similar configuration in its sip-communicator file to configure the same MUC, e.g.:

`org.jitsi.jicofo.jibri.SIP_BREWERY=SipBrewery@xx.xx.xx`

**Comment by fuqiangleon** [comment]
thank you sir, but how can i set sip muc of jibri ?eg sip account id ,password etc ?
is there any docs to introduce that ? 

have a nice day.

**Comment by bbaldino** [comment]
We use pjsua for the client and although we pass in some of the arguments explicitly, we also point to a a config file (the command we run is [here](https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/sipgateway/pjsua/executor/PjsuaExecutor.kt#L63), and the location of the config file is defined [here](https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/sipgateway/pjsua/executor/PjsuaExecutor.kt#L41)).  So you could add some arguments to the config file and they should get passed through to pjsua.

**Comment by bbaldino** [comment]
That config, by the way, is totally separate from the SIP MUC: the MUC Jibri joins is to advertise its capability as being SIP-capable to Jicofo.  Only if that happens will a client be able to request a SIP gateway call and have Jicofo forward the request to Jibri (which will contain the SIP address, etc. to call) and then actually start the pjsua client with the args discussed above.

**Comment by fuqiangleon** [comment]
thank you sir @bbaldino  ,we will try it

**Comment by fuqiangleon** [comment]
@bbaldino  
I have installed the pjsua , are there something need to be config ? sorry , i can not find any documents about pjsua configuation in config.json of jibri.

hope get your help

Thank you very much.

**Comment by bbaldino** [comment]
Let's keep this discussion on the community (where I see you already have a post).

**Comment by mustahsin64** [comment]
> 

hi @bbaldino. Can you please share the config file and its path again, Its saying 404 not found
