### ISSUE TITLE
Jibri doesn't record. No Jibri found to the Jicofo

### ISSUE THREAD

**Issue by abhijitnathwani** [jitsi/jibri#145]
Hi,
I have installed Jibri and made the necessary config changes across Jitsi-Meet/Jicofo/Prosody as mentioned in the README file. However, I am still not able to record the conference. The recording button is enabled but when I click it, the recording unavailable pops up.

In the Jicofo logs, I see ```Jicofo 2018-08-24 17:48:23.802 SEVERE: [87] org.jitsi.jicofo.recording.jibri.JibriSession.log() Unable to find an available Jibri, can't start
Jicofo 2018-08-24 17:48:23.803 INFO: [87] org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Failed to start a Jibri session, no Jibris available```.

Please help me out here. Find the attached logs and config files.

[log.0.txt](https://github.com/jitsi/jibri/files/2318365/log.0.txt)
[jicofo.log](https://github.com/jitsi/jibri/files/2318366/jicofo.log)
[jibri-config.txt](https://github.com/jitsi/jibri/files/2318367/config.txt)
[10.115.3.28-config.txt](https://github.com/jitsi/jibri/files/2318368/10.115.3.28-config.txt)

**Comment by abhijitnathwani** [comment]
So how do I resolve that ? Any ideas for to debug that?

Regards,
Abhijit Nathwani

**Comment by bbaldino** [comment]
I don't believe `prod.xmpp.10.115.3.28` is a proper hostname.  I'm guessing you configured `prod.xmpp` for a subdomain, but for the xmpp host you put in an IP directly.  You need to use the hostname for the xmpp host, so you end up with something like `prod.xmpp.my-xmpp-server.com`

**Comment by abhijitnathwani** [comment]
Hi @bbaldino ,
I am not able to figure out the following configurations. I guess I'm messing up here. The XMPP server is the Prosody service, right? I have Prosody running on the same system as Jibri. All my services work on IP. I don't have a hostname on the local environment.

 "xmpp_environments": [
        {
            // A friendly name for this environment which can be used
            //  for logging, stats, etc.
            "name": "prod environment",
            // The hosts of the XMPP servers to connect to as part of
            //  this environment
            "xmpp_server_hosts": [
                "prod.xmpp.10.115.3.28"
            ],
            // The xmpp domain we'll connect to on the XMPP server
            "xmpp_domain": "xmpp.10.115.3.28",
            // Jibri will login to the xmpp server as a privileged user
            "control_login": {
                // The domain to use for logging in
                "domain": "auth.xmpp.10.115.3.28",
                // The credentials for logging in
                "username": "jibri",
                "password": "XXXXX"
            },

**Comment by damencho** [comment]
Check with netstat whether port 5222 is open on that ip address, by default prosody listen only on localhost. Or just change your config to use 127.0.0.1 if both prosody and jibri are on the same machine.

**Comment by abhijitnathwani** [comment]
Hi @damencho ,

```
root@abhijit:/usr/local/sbin# netstat -ntpl | grep 5222
tcp        0      0 0.0.0.0:5222            0.0.0.0:*               LISTEN      24056/lua5.1
tcp6       0      0 :::5222                 :::*                    LISTEN      24056/lua5.1
```

5222 is open. I didn't understand which config are you talking about. I have uploaded the configs above in the issue. Can you please check them.?

Prosody config: 
[prosody.cfg.lua.txt](https://github.com/jitsi/jibri/files/2324007/prosody.cfg.lua.txt)

**Comment by damencho** [comment]
I'm talking about 
```
"xmpp_server_hosts": [
                "prod.xmpp.10.115.3.28"
            ],
```
Have you tried setting it as:
```
"xmpp_server_hosts": [
                "127.0.0.1"
            ],
``` ?

**Comment by bbaldino** [comment]
Also, so are you running all jitsi-meet services (jicofo, jvb, prosody, etc.) on that same machine?

**Comment by abhijitnathwani** [comment]
Hi @damencho ,
I tried setting it as the localhost, but no, it does not help. The same logs. No jibris found.

@bbaldino yes I'm running all the services on the same machine. Everything works fine, even Jigasi, just Jibri is not able to run. Some config changes we are missing out.

**Comment by tvirpariya123** [comment]
Hi @damencho,

I faced same issue, XMPP server not authenticated and I am not able to record a file, even record button  is enabled and also ask confirmation.

Please guide to configure jibri config file properly, and I also install all service on same machin on same IP.

**Comment by abhijitnathwani** [comment]
It was the XMPP server connection issue. Installed Jibri on some other system than the Jitsi-Meet and configured the IPs properly and it works now. The recording is started. Thanks for the help guys.

**Comment by bbaldino** [comment]
Jibri is unable to connect to your xmpp server:

```
2018-12-01 07:06:10.481 SEVERE: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Error connecting to xmpp environment: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'prod.xmpp.new.mykensho.com:5222' failed because: java.net.UnknownHostException: prod.xmpp.new.mykensho.com: Name or service not known
```
Looks like that host isn't resolving

**Comment by alexis619** [comment]
@bbaldino @damencho then how should i provide the xmpp server name in jibri. Need to specify only the the domain name as xmpp server name or need to prod.xmpp.domainname.

Please help me to figure out this issue.

**Comment by abhijitnathwani** [comment]
Hi @alexis619 ,

Please use only the xmpp server name. No need to add the prod. subdomain. Please have a look at this [video](https://www.youtube.com/watch?v=OHHoqKCjJ0E&t=1014s) to help understand the setup of Jibri and the config changes.

Regards,
Abhijit

**Comment by alexis619** [comment]
Hi@abhijitnathwani ,
 I have tried giving the domain name only, then also i am facing the same problem.
Please help me to figure out this issue.

Regards,
Alexis

**Comment by alexis619** [comment]
@bbaldino @damencho @abhijitnathwani 

I have installed and tried the specific kernel type, but then also it shows same error.

I have followed all the steps except this command --> modprobe snd-aloop (getting error):

root@jibri:~#modprobe snd-aloop
modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/4.4.0-1073-aws

I am ubuntu 16.04 LTS

Please suggest me how to install ALSA and Loopback Device.

**Comment by aaronkvanmeerten** [comment]
Have you rebooted the instance into the new kernel you installed?  Also this is not an issue related to jibri connection, so please try to reach out in the community.jitsi.org forums to ask these sorts of questions, which are unrelated to the original topic of this issue.

**Comment by tvirpariya123** [comment]
Hi @aaronkvanmeerten 

Jibri has many issues regarding audio. The main issue is the recorded video file does not contain audio. We have many community members facing the same problem and posted on the community, but have not found any answer yet. Could you please help us out on this issue? We have threads running on Jibri audio issue here: https://community.jitsi.org/t/help-error-jibri/15998/40

Thanks.

**Comment by aaronkvanmeerten** [comment]
Thanks for the ping.  I fear that @virtuacoplenny has indicated there's a problem in the newer chrome versions around GUM not being activated due to lack of user interaction.  I will work with @bbaldino and @virtuacoplenny to try to find the workaround.  In the meantime perhaps try jibri with an older chrome and see if this resolves it?  I'll comment on the community as well.

**Comment by alexis619** [comment]
@bbaldino @damencho, I am having my own jitsi server in Sydney region in aws. But person1 from australia and person2 from India tries to have desktop sharing and its works fine for 5 mins. And person1 in australia gets a bandwidth connectivity issue , please help me to rectify and solve the issue.

**Comment by alexis619** [comment]
@aaronkvanmeerten ,how to add the secondary jvb to the main jitsi-meet server. Please  provide me the steps or provide me any links to refer and resolve the issue

**Comment by damencho** [comment]
@alexis619 please stop posting questions in random issues. We prefer having the discussions in our community forum. https://community.jitsi.org
If you have a question or a problem, create a topic there and ask. Do not hijack different topics.

**Comment by abhijitnathwani** [comment]
Hi @alexis619 ,

Try posting on [community](https://community.jitsi.org/) first, before posting on Github. The community is active and people reply there.

Abhijit
