### ISSUE TITLE
No audio in Jibri recording.

### ISSUE THREAD

**Issue by abhijitnathwani** [jitsi/jibri#146]
Hi,
I have successfully connected the Jibri to Jitsi and recording and live streaming to youtube is working fine now. However, in the recorded .mp4 file, I don't have any audio. Even the video as audio channel with some packets but cannot hear.

I do have the ```.asoundrc``` file in the ```/home/jibri``` folder.

```
jibri@AHMCPU0130:~$ cat .asoundrc
# playback PCM device: using loopback subdevice 0,0
pcm.amix {
  type dmix
  ipc_key 219345
  slave.pcm "hw:Loopback,0,0"
}

# capture PCM device: using loopback subdevice 0,1
pcm.asnoop {
  type dsnoop
  ipc_key 219346
  slave.pcm "hw:Loopback,0,1"
}

# duplex device combining our PCM devices defined above
pcm.aduplex {
  type asym
  playback.pcm "amix"
  capture.pcm "asnoop"
}

# ------------------------------------------------------
# for jack alsa_in and alsa_out: looped-back signal at other ends
pcm.ploop {
  type plug
  slave.pcm "hw:Loopback,1,1"
}

pcm.cloop {
  type dsnoop
  ipc_key 219348
  slave.pcm "hw:Loopback,1,0"
}

# ------------------------------------------------------
# default device

pcm.!default {
  type plug
  slave.pcm "aduplex"
}jibri@AHMCPU0130:~$
```

Also, the output of ```arecord -l```.

```
jibri@AHMCPU0130:~$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 7/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: PCH [HDA Intel PCH], device 0: CX20641 Analog [CX20641 Analog]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 2: CX20641 Alt Analog [CX20641 Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
jibri@AHMCPU0130:~$
```

**Comment by Ark74** [comment]
Do you mind sharing some of the config files?
Thanks

**Comment by abhijitnathwani** [comment]
Hi @Ark74 

Please find the attached config files.

[jicofo-sip-communicator.properties.txt](https://github.com/jitsi/jibri/files/2370843/jicofo-sip-communicator.properties.txt)
[jibri-config.json.txt](https://github.com/jitsi/jibri/files/2370849/jibri-config.json.txt)
[jitsi-meet-config.txt](https://github.com/jitsi/jibri/files/2370850/jitsi-meet-config.txt)

**Comment by Ark74** [comment]
Thank you very much,
For prosody, did you appended the changes to /etc/prosody/conf.d/domain.com.cfg.lua or directly to /etc/prosody/prosody.conf ?

Also, what is the output of `modprobe snd-aloop` ?

**Comment by abhijitnathwani** [comment]
Hi,
I did the changes in ``` /etc/prosody/conf.d/domain.com.cfg.lua```.

```
tejas@AHMCPU0130:~$ modprobe snd-aloop
tejas@AHMCPU0130:~$ lsmod | grep snd_aloop
snd_aloop              24576  0
snd_pcm                98304  5 snd_hda_intel,snd_hda_codec,snd_hda_core,snd_hda_codec_hdmi,snd_aloop
snd                    81920  12 snd_hda_intel,snd_hwdep,snd_hda_codec_conexant,snd_seq,snd_hda_codec,snd_timer,snd_rawmidi,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_seq_device,snd_aloop,snd_pcm

```

**Comment by Ark74** [comment]
Ok, your card is detected and driver loaded, that should be good ;)
Just asking, do you run any other app that might be using audio resources?

2 months ago I got it working just fine, and so far, can't even enable recording. :worried:

**Comment by abhijitnathwani** [comment]
Hi @Ark74 ,

Nope. No other apps using audio resources.

**Comment by Ark74** [comment]
Test with local recording.

```
//Local Recording 
    localRecording: {
    enabled: true,
    format: 'flac'
    }
```
If it works (as in there is sound), then it might be a deeper issue on jibri.

Also make sure you are using a valid ssl cert, since modern browsers do a lot of work behind the scenes, and it would be better to avoid "blocked mixed content" issues.

**Comment by cheechmarino** [comment]
Hi @Ark74 
> 2 months ago I got it working just fine, and now so far, can't even enable recording. 😟
 Do you see recording button at menu?

We've found that because of unstable repository, which is added on jibri install, latest jitsi updates are installed from that repository and recording button is missing after that.

**Comment by Ark74** [comment]
Well indeed, unstable gets brand new features which you really need to pay attention or they go overlooked.

There is a new requirement to use jibri recording if you are using the latest release.
* Dropbox app key element.

Cheers!

**Comment by abhijitnathwani** [comment]
I got it working by solving the ffmpeg issues. The ffmpeg version I had some broken packages. I recommend using ffmpeg v3.4+ for jibri. For the recording buttons, the Jitsi Meet config takes care of that.

**Comment by cheechmarino** [comment]
> There is a new requirement to use jibri recording if you are using the latest release.
>     * Dropbox app key element.
> Cheers!

Can you please describe little bit more precisely about "Dropbox app key element"? How can we enable this requirement? Because Recording button is missing on system with latest Jitsi stable release.

Thanks.

**Comment by damencho** [comment]
@cheechmarino You can obtain a Dropbox app key from https://www.dropbox.com/developers/apps

**Comment by cheechmarino** [comment]
@damencho we are missing recording button from right bottom corner menu. Right after updating Jitsi (and all Jitsi related components) to latest stable version. I've triple checked all configs (recording and live streaming both are set to true, recording button is enabled at /usr/share/jitsi-meet), but unfortunately was unable to find how to get recording button back. 
Will Dropbox app key resolve this issue? If yes, where I should enter it?

**Comment by Ark74** [comment]
Carefully looking for it :wink: 
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L174

**Comment by damencho** [comment]
Yes, dropbox is a requirement for recording in current release. We are planning to revert this requirement and leave it as it used to be and to release it soon in stable.

**Comment by cheechmarino** [comment]
@Ark74 Thanks!

Added dropbox to configuration, but still there is no Recording button:
    fileRecordingsEnabled: true,
    dropbox: {
        appKey: '525za538bn3h7bh' //only appKey, without appSecret (this is not real appKey)
    },
    liveStreamingEnabled: true,

**Comment by Ark74** [comment]
If you had jibri operating before, that's the only change I can think of you needed to add/update.
In case this is the first time you enable Jibri, then you might wanna look for the check the [documentation](https://github.com/jitsi/jibri#jibri).

Debian packages works just fine.

**Comment by cheechmarino** [comment]
Yes, Jibri was operating before. I have one more Jitsi installation on VM with snapshots. There is working version. So I will do some test on that environment.  Dropbox services should be available from server where Jitsi is installed?

**Comment by Ark74** [comment]
> So I will do some test on that environment.

Good idea.

> Dropbox services should be available from server where Jitsi is installed?

Not really sure of what you mean, but don't worry to much about Dropbox, as several developers had said, the dropbox requirement will be revert (soon).

Cheers!

**Comment by cheechmarino** [comment]
Hi. After some investigation we can tell that when using below versions, recording button is present in menu 
![rec_button_jitsi](https://user-images.githubusercontent.com/24827950/46529169-6635f400-c89e-11e8-97a7-03eb5ef3cf7a.png)
 and recording is working (mp4 file is created inside server's "recording_directory" folder):
jibri 5.1.58-1
jicofo 1.0-425-1 
jitsi-meet 1.0.3229-1
jitsi-meet-prosody 1.0.2942-1
jitsi-meet-web 1.0.2942-1
jitsi-meet-web-config 1.0.2942-1
jitsi-videobridge 1077-1

But when we updating Jitsi to versions below (latest stable):
jibri  5.1.58-1
jicofo  1.0-437-1
jitsi-meet 1.0.3344-1
jitsi-meet-prosody 1.0.3036-1
jitsi-meet-web  1.0.3036-1
jitsi-meet-web-config 1.0.3036-1
jitsi-videobridge 1087-1

recording button is missing. 
![rec_button_missing_jitsi](https://user-images.githubusercontent.com/24827950/46529838-941c3800-c8a0-11e8-9d16-b7637862a6b8.png)

Dropbox is added to config 
![jitsi_meet_conf](https://user-images.githubusercontent.com/24827950/46529778-66cf8a00-c8a0-11e8-9a95-301c7c69127e.png)

**Comment by Ark74** [comment]
Recording is not available on stable just yet.
AFAIK, it is planned to be released soon.

Also, please try not to hijack the thread, I would say check the READMEs since this isn't a bug.
