### ISSUE TITLE
Error CallPage.visit() Timed out waiting for call page to load

### ISSUE THREAD

**Issue by pekubu** [jitsi/jibri#149]
I'm run jitsi-meet and jibri on the same server.
When clicking on Start Recording it says "preparing to record the meeting" and after a while "Recording failed to start".
[browser.log](https://github.com/jitsi/jibri/files/2392011/browser.log)
[jibri.log](https://github.com/jitsi/jibri/files/2392019/jibri.log)

`c2s_require_encryption = true
consider_bosh_secure = true
`
I have add it to prosody

**Comment by bbaldino** [comment]
Nothing jumping out from the logs--unfortunately we don't get much info for scenarios like this.  Could it be legitimate?  Can your Jibri machine access the url?

**Comment by pekubu** [comment]
I reinstall it, it working.
