### ISSUE TITLE
Running Jibri with Jitsi-Meet application to record audio

### ISSUE THREAD

**Issue by shehrozekhan** [jitsi/jibri#15]
Can someone please explain how we can use jibri to record audio for a multi-user conference in Jitsi Meet? I have cloned the repo but I don't understand how to run the shell to record audio for a conference. The documentation is not very clear on this. Any help would be highly appreciated!

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian respository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
