### ISSUE TITLE
Audio with gaps

### ISSUE THREAD

**Issue by cheechmarino** [jitsi/jibri#153]
## Description
Hi Everyone! After meeting is successfully recorded MP4 file's audio stream contains gaps (aprox. every 4 secs.). It happens with every recorded meeting. Please see MP4 (zipped) file in attachment.

## Current behavior
MP4 audio stream with gaps.

## Expected Behavior
Continuous audio

## Possible Solution
---

## Steps to reproduce
Record meeting.
[audiotest_2018-09-27-15-33-45.zip](https://github.com/jitsi/jibri/files/2424086/audiotest_2018-09-27-15-33-45.zip)

# Environment details
Ubuntu 16.04.5 LTS
ii jibri 5.0.57-1
ii jicofo 1.0-425-1
ii jitsi-meet 1.0.3229-1
ii jitsi-meet-prosody 1.0.2942-1
ii jitsi-meet-web 1.0.2942-1
ii jitsi-meet-web-config 1.0.2942-1
ii jitsi-videobridge 1077-1

**Comment by aaronkvanmeerten** [comment]
What type of machine is running the ffmpeg process? We found we needed to use a fairly powerful CPU (c4.xlarge in AWS) and that consistent video performance required a Dedicated tenancy in AWS.

**Comment by cheechmarino** [comment]
> Can you please attach all the jibri logs.
> 
> Did the video have any issues? EDIT: Just saw that the file has video as well, however the image makes it hard to tell if there are freezes happening or not. Maybe you can point the camera at something that moves consistently.

Please see attached files for new MP4 file (video + audio) and Jibri logs.
[testaudvid_2018-10-01-12-04-23.zip](https://github.com/jitsi/jibri/files/2433361/testaudvid_2018-10-01-12-04-23.zip)
[jibrilogs.zip](https://github.com/jitsi/jibri/files/2433362/jibrilogs.zip)

**Comment by bbaldino** [comment]
I don't see any complaints about underruns or anything in the ffmpeg logs, so it doesn't appear the issue is coming from that layer.  Some other things to check:

1) If you join as a client on that machine (manually, instead of it running jibri), do audio and video work fine?
2) Do other clients in the call experience the same audio issues?

**Comment by cheechmarino** [comment]
There is no issues inside meeting itself. Users don't experience audio gaps when they are joined meeting. Both, audio and video streams are fine. Issue persists only when meeting is recorded, and only with audio stream in MP4 recorded file.

**Comment by bbaldino** [comment]
Are you 'watching' the Jibri client join?  As in, can you watch Jibri join on the machine and hear the audio/see the video that it's recording from?  Do you hear the audio issues there?

**Comment by cheechmarino** [comment]
@bbaldino Sorry. Can you please tell how can I do that?

**Comment by bbaldino** [comment]
From what I could tell the way you described the machine running Jibri was a computer with a monitor attached, right?  I just meant to watch that computer "from Jibri's perspective" as it launches the client to join the call and see if the issue is present.

**Comment by cheechmarino** [comment]
Correct. This is HP notebook. But it has Debian installation without GUI, only CLI is available. How can we "watch that computer "from Jibri's perspective" as it launches the client to join the call and see if the issue is present."? Thanks!!!

**Comment by bbaldino** [comment]
You'd have to launch the same desktop that jibri will use when it starts selenium.

**Comment by Ark74** [comment]
@cheechmarino I had a hard time configuring jibri too.
You may wanna try:
https://github.com/switnet-ltd/quick-jibri-installer

It should help you test your hardware and connections.
Cheers

**Comment by cheechmarino** [comment]
@Ark74 :))) Thanks. I will deploy one more test environment on different hardware. Will try to reproduce issue. If not, then it's hardware related issue.

**Comment by cheechmarino** [comment]
Thank you All for help!!! Same installation but on different hardware without monitors works perfect.
 Thanks one more time!
