### ISSUE TITLE
Jibri uses too much memory.

### ISSUE THREAD

**Issue by pekubu** [jitsi/jibri#154]
My jibri running server has a ram = 2GB, but when launching jibri, memory is only ~ = 50MB. I can not turn off jibri.
![image](https://user-images.githubusercontent.com/26251116/46993227-5046ef80-d138-11e8-83b7-fe143ec109f3.png)
What is the reason, the minimum ram for each room is?
Thank you so much.

**Comment by saghul** [comment]
2GB of RAM is not going to be enough. Jibri works by spawning a Chrome browser and recording its output. This is in addition to a window manager and the ffmpeg process doing the recording.
