### ISSUE TITLE
unable to see video stream button on in jitsi-meet 

### ISSUE THREAD

**Issue by tarlesurendra** [jitsi/jibri#16]
Hello,

We have installed jits-meet on our site https://jetsofts.com and its working but we are unable to see start/stop video stream option on that and also we have tried to install all needed packages for jibri but live streaming is not working and we hope we get needful help here.
awaiting for the response.

Thank you

**Comment by tarlesurendra** [comment]
Please help me in that issue and its very important for me and i hope this will very useful for us.

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian respository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
