### ISSUE TITLE
SSL handshake issue

### ISSUE THREAD

**Issue by magatz** [jitsi/jibri#18]
My setup: jibri runs on a separate machine from jitsi-meet, plain setup:
Prosody logs can see the incoming connection but sleekxmpp complains about TLS negotiation.
The prosody server uses a valid certificate (wildcard, used even for https)

Tried with both sleekxmpp 1.3.1 and 1.4.0 on ubuntu 1server 16.04

Negotiating TLS
2016-09-11 09:04:46,941 INFO     Using SSL version: TLSv1
2016-09-11 09:04:46,980 ERROR    Could not match certificate against hostname: ww.example.com

Any suggestion?

**Comment by debugmaster** [comment]
Is your hostname resolvable through real DNS? dnspython doesn't use entries from /etc/hosts.

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian respository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
