### ISSUE TITLE
Unable to find an available Jibri, can't start

### ISSUE THREAD

**Issue by mohsalxedflix** [jitsi/jibri#181]
Failed to start a Jibri session, no Jibris available

Jibri log
[log.0.txt](https://github.com/jitsi/jibri/files/2768367/log.0.txt)

Jibro config
[config.txt](https://github.com/jitsi/jibri/files/2768374/config.txt)

Jibri version:
jibri is already the newest version (7.1.70-1).

Jitsi Meet version:
jitsi-meet is already the newest version (1.0.3493-1).

Both were installed from unstable

**Comment by bbaldino** [comment]
Are you running Jibri with java 9?  There's an error in the Jibri logs that looks like it may be related to that (we've only run jibri with java 8)

**Comment by mohsalxedflix** [comment]
Issue resolved. Thanks.

**Comment by matthiasg** [comment]
> Issue resolved. Thanks.

how was it resolved ?
