### ISSUE TITLE
Is it possible to  increase the Jibri instances dynamically ?

### ISSUE THREAD

**Issue by andaralex** [jitsi/jibri#187]
any idea for creating "N" instances (100 to 200) dynamically for multiple recording at the same time based on session created? 

Is it efficient? Also, what's your opinion in cost wise?

Is there any other solution to implement this, like a docker image of Jibri? Anyone from this community to help us for contribute basis?

**Comment by idistech** [comment]
+1

**Comment by bbaldino** [comment]
This is better suited for the [community forum](https://community.jitsi.org/).  But yes, Jibris can be created and used dynamically, they just need to be spun up and join the MUC and Jicofo will see and use them.

We don't use docker for Jibri currently, though there are people playing with it.

**Comment by strasharo** [comment]
When multiple Jibri instances are used, should they use unique users for prosody or it's fine to have the same two accounts on all of them?

**Comment by bgrozev** [comment]
They can use the same XMPP account, they just need a different nickname in the MUC
