### ISSUE TITLE
Record separately audio

### ISSUE THREAD

**Issue by qnkhuat** [jitsi/jibri#191]
Hi, I've been recording for a while but my audio output is mixed audio from both participants.
I want to get the audio source of audio separately. 
Any idea to complete this?
Thanks

**Comment by bbaldino** [comment]
This isn't possible with Jibri, Jibri joins the call like a normal client and captures the audio output after it's been mixed.

**Comment by bbaldino** [comment]
If you want to discuss further, open a topic over on [the community](https://community.jitsi.org/) and we can chat there.
