### ISSUE TITLE
Error starting Jibri service : java.lang.StringIndexOutOfBoundsException: String index out of range: -1 with stack

### ISSUE THREAD

**Issue by pppppswang** [jitsi/jibri#198]
Sorry i see #185 fixed the problem #184 ,but when i download the newest jibri(version 7.2.71-1) and started recording, still reported the same error. I don't know what went wrong. Could you help me? Thank you very much.

> 2019-06-02 21:32:21.944 SEVERE: [38] org.jitsi.jibri.api.xmpp.XmppApi.run() Error starting Jibri service : java.lang.StringIndexOutOfBoundsException: String index out of range: -1 with stack: 
java.lang.String.substring(String.java:1967)
java.lang.String.subSequence(String.java:2003)
org.jitsi.jibri.util.XmppUtilsKt.getCallUrlInfoFromJid(XmppUtils.kt:38)
org.jitsi.jibri.api.xmpp.XmppApi.handleStartService(XmppApi.kt:276)
org.jitsi.jibri.api.xmpp.XmppApi.access$handleStartService(XmppApi.kt:71)
org.jitsi.jibri.api.xmpp.XmppApi$handleStartJibriIq$1.run(XmppApi.kt:200)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by bbaldino** [comment]
Would you be able to give us the room name and domain you're using which crashes?  (Maybe obfuscated?)

**Comment by pppppswang** [comment]
muc: conference.jitsi.wangppess.club

**Comment by pppppswang** [comment]
config.js
> hosts: {
        // XMPP domain.
        domain: 'jitsi.wangppess.club',

        // When using authentication, domain for guest users.
        // anonymousdomain: 'guest.example.com',

        // Domain for authenticated users. Defaults to <domain>.
        // authdomain: 'jitsi.wangppess.club',

        // Jirecon recording component domain.
        // jirecon: 'jirecon.jitsi.wangppess.club',

        // Call control component (Jigasi).
        // call_control: 'callcontrol.jitsi.wangppess.club',

        // Focus component domain. Defaults to focus.<domain>.
        // focus: 'focus.jitsi.wangppess.club',

        // XMPP MUC domain. FIXME: use XEP-0030 to discover it.
        muc: 'conference.jitsi.wangppess.club'
    },

    // BOSH URL. FIXME: use XEP-0156 to discover it.
    bosh: '//jitsi.wangppess.club:7443/http-bind',

**Comment by pppppswang** [comment]
below is jibri log:

> 2019-06-03 13:35:15.120 INFO: [24] org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq() Received JibriIq <iq to='jibri@auth.hello.wangppess.club/e30fed35-2fec-4bc8-9e80-634273200eb6' from='jibribrewery@internal.auth.hello.wangppess.club/focus' id='amlicmlAYXV0aC5oZWxsby53YW5ncHBlc3MuY2x1Yi9lMzBmZWQzNS0yZmVjLTRiYzgtOWU4MC02MzQyNzMyMDBlYjYARWR4a2ktNzQ1NgDEFBG4unlHngIPdM5cjeim' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='start' recording_mode='file' room='hello@conference.jitsi.wangppess.club' session_id='wgjarpfusjeinrvb' app_data='{"file_recording_metadata":{"share":true}}'/></iq> from environment test
2019-06-03 13:35:15.121 INFO: [24] org.jitsi.jibri.api.xmpp.XmppApi.handleStartJibriIq() Received start request
2019-06-03 13:35:15.121 INFO: [24] org.jitsi.jibri.api.xmpp.XmppApi.handleStartJibriIq() Sending 'pending' response to start IQ
2019-06-03 13:35:15.121 INFO: [39] org.jitsi.jibri.api.xmpp.XmppApi.run() Starting service
2019-06-03 13:35:15.121 SEVERE: [39] org.jitsi.jibri.api.xmpp.XmppApi.run() Error starting Jibri service : java.lang.StringIndexOutOfBoundsException: String index out of range: -1 with stack: 
java.lang.String.substring(String.java:1967)
java.lang.String.subSequence(String.java:2003)
org.jitsi.jibri.util.XmppUtilsKt.getCallUrlInfoFromJid(XmppUtils.kt:38)
org.jitsi.jibri.api.xmpp.XmppApi.handleStartService(XmppApi.kt:276)
org.jitsi.jibri.api.xmpp.XmppApi.access$handleStartService(XmppApi.kt:71)
org.jitsi.jibri.api.xmpp.XmppApi$handleStartJibriIq$1.run(XmppApi.kt:200)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by pppppswang** [comment]
How can I find out the problem?Please help.

**Comment by bbaldino** [comment]
@damencho will probably have a better eye for this than me, but I'm assuming a mismatch of the configured domain and the domain in the jid?

**Comment by pppppswang** [comment]
Should I configure the same domain name as meet in prosody?

**Comment by pppppswang** [comment]
Should I configure the same domain name as meet in prosody? I configured 'hello. wangppess. club' in prosody and 'jitsi. wangppess. club' in meet.

**Comment by damencho** [comment]
> Should I configure the same domain name as meet in prosody? I configured 'hello. wangppess. club' in prosody and 'jitsi. wangppess. club' in meet.

I cannot understand your config, 'hello. wangppess. club'  what do you use it for?

**Comment by pppppswang** [comment]
Sorry, this error is due to my misconfiguration, thank you very much
