### ISSUE TITLE
Use virtual soundcard for recording

### ISSUE THREAD

**Issue by zdila** [jitsi/jibri#20]
Using hardware soundcard limits to only single recording per machine. You can consider using virtual soundcards with pulse audio:
```
#!/bin/bash

UUID=`uuidgen`
MID=`pactl load-module module-null-sink sink_name=$UUID`
pacmd update-sink-proplist $UUID device.description=$UUID

DISPLAY=:$DISP PULSE_SINK=$UUID google-chrome --kiosk --user-data-dir=chrome-$UUID.tmp https://www.youtube.com/watch?v=hSwg4fIgthU &

PULSE_SOURCE=$UUID.monitor ffmpeg -y \
  -video_size 800x600 -framerate 30 -r 30 -f x11grab -draw_mouse 0 -i :$DISP.0 \
  -f pulse -i default -vcodec libx264 -preset fast output-$UUID.mp4 &

# wait until done

pactl unload-module $MID
```

Also note the `-draw_mouse 0` parameter so you don't need to move the pointer to the edge of the screen.

**Comment by debugmaster** [comment]
It already uses virtual soundcards with module aloop from ALSA. But is is still limited to 8.

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian respository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
