### ISSUE TITLE
Bug coming from ChromeDriver 75

### ISSUE THREAD

**Issue by netaskd** [jitsi/jibri#202]
## Description
---
After update Chrome driver up to 75.0.3770.8 and Chrome up to 75.0.3770.90
recording can not be stopped properly. Log here: https://pastebin.com/aB9eKXTs
I guess, the main reason in this exeption:
``[48] org.jitsi.jibri.util.JibriSubprocess.ffmpeg.stop() Stopping ffmpeg process
org.openqa.selenium.UnsupportedCommandException: unknown command: Cannot call non W3C standard command while in W3C mode``

## Possible Solution
---
Folks from https://stackoverflow.com/questions/56111529/cannot-call-non-w3c-standard-command-while-in-w3c-mode-seleniumwebdrivererr suggests solution.

## Steps to reproduce
---
1. Update Chrome and ChromeDriver to 75
2. Start recording, then stop recording
3. Read logs

**Comment by bbaldino** [comment]
Thanks for reporting.  I'm looking at some other Jibri stuff so will try and look at this soon.

**Comment by bbaldino** [comment]
Fixed in https://github.com/jitsi/jibri/pull/205
