### ISSUE TITLE
Chrome 76 shows in recorded file "chrome is being controlled by automated software"

### ISSUE THREAD

**Issue by netaskd** [jitsi/jibri#208]
## Description
---
Since chrome 76 the option "--disable-infobars" has been removed, which could previously be used to hide pop-up warnings in the Chrome interface (the CommandLineFlagSecurityWarningsEnabled rule has been proposed for hiding security-related warnings);
Option is here: https://github.com/jitsi/jibri/blob/845cc3274eeea14ad026417f5bfb2d44f06dcedb/src/main/kotlin/org/jitsi/jibri/selenium/JibriSelenium.kt#L134

## Possible Solution
---
the CommandLineFlagSecurityWarningsEnabled rule has been proposed for hiding security-related warnings. 
https://www.chromium.org/administrators/policy-list-3#CommandLineFlagSecurityWarningsEnabled

## Steps to reproduce
---
1. Update Chrome up to 76
2. Do record a conference
3. Open the recorded file
4. In the top of the recorded file you will see "chrome is being controlled by automated software"

# Environment details
---
Linux 3.10.0-957.27.2.el7.x86_64
ChromeDriver 75.0.3770.140
Google Chrome 76.0.3809.87
jibri 7.7.76-1

**Comment by saghul** [comment]
Maybe this is also a solution? https://github.com/GoogleChrome/puppeteer/issues/2070#issuecomment-516694574

**Comment by bbaldino** [comment]
Cool I'll try the solution from Puppeteer at some point.  @netaskd feel free to open a PR, we already have code passing  experimental options.

**Comment by dbkr** [comment]
This just bit us when upgrading chrome. For the benefit of anyone who needs to work around this until jibri is updated, the flag @netaskd mentions can be used by creating the file `/etc/opt/chrome/policies/managed/managed_policies.json` with contents:
```
{
  "CommandLineFlagSecurityWarningsEnabled": false
}
```

**Comment by netaskd** [comment]
Thanks @dbkr!
I think it's the best way to disable warnings, because:
1. setting via setExperimentalOption is unstable and can be changed in any next releases.
2. do not need re-compilation of the jibri package, can be changed on fly.

**Comment by netaskd** [comment]
@bbaldino added PR #210

**Comment by sergiistupkin** [comment]
Since "--disable-infobars" has been removed from Chrome 76, there is the solution: https://support.google.com/chrome/a/answer/187202 
This is works for me.

**Comment by jbrundige** [comment]
Hello!

I tried @dbkr 's solution but I am running Chrome 81 and I think that's why it doesn't work. Anybody know how to disable this in Chrome 81? Thank you!
