### ISSUE TITLE
Could not connect jibri with jitsi

### ISSUE THREAD

**Issue by shubhamblue** [jitsi/jibri#244]
Hi,

I have set up two separate VM's for jitsi and jibri. I followed the following tutorials for configuration.
jitsi : https://www.youtube.com/watch?v=OHHoqKCjJ0E
jibri: https://www.youtube.com/watch?v=8KR0AhDZF2A

When I try to record meet. It shows recording failed to start.
In jibri logs I am seeing that Jibri is trying to connect to meet.mollatech.com/192.168.0.196 where 192.168.0.196 is not static IP.

Ubuntu servers used for Jitsi and Jibri : 16.04.6 LTS
Jitsi meet version : 1.0.4101-1
Jicofo version: 1.0-508-1
Jibri version : 8.0-14-g0ccc3f6-1

I have added Jicofo, Jibri logs
[jicofo.log](https://github.com/jitsi/jibri/files/4328865/jicofo.log)
[log.9.txt](https://github.com/jitsi/jibri/files/4328882/log.9.txt)

**Comment by bbaldino** [comment]
Jibri says it can't connect to the xmpp server.  Do you maybe have an `/etc/hosts` entry for `meet.mollatech.com` or something from before?  Is the server accessible from the Jibri machine?

**Comment by shubhamblue** [comment]
Hi @bbaldino thanks for your quick response.
Yup I had entry for meet.mollatech.com for diffrent ip.  My bad
