### ISSUE TITLE
Jibri recording failed Failed to read the 'localStorage' property from 'Window': Access is denied for this document

### ISSUE THREAD

**Issue by shubhamblue** [jitsi/jibri#246]
Hi,

I already looked for the possible solutions for the problem on jitsi community and github issues but still not able to solve the problem.

Ubuntu servers used for Jitsi and Jibri : 16.04.6 LTS
Jitsi meet version : 1.0.4101-1
Jicofo version: 1.0-508-1
Jibri version : 8.0-14-g0ccc3f6-1
Chrome drivers are latest stable version

I am attaching jibri logs and jicofo logs
[jicofo.log](https://github.com/jitsi/jibri/files/4343308/jicofo.log)
[log.0.txt](https://github.com/jitsi/jibri/files/4343309/log.0.txt)

Thanks in advance

**Comment by sharkme** [comment]
i got have the same problem ,did you have any solution?

**Comment by danielarbo** [comment]
Same problem usign Docker

**Comment by shubhamblue** [comment]
@sharkme no solution yet

**Comment by TinNguyen331** [comment]
i got same problem when install 2 VMs Jitsi, Jibri

**Comment by sharkme** [comment]
its seems that change the url from callUrlInfo.baseUrl to "http://127.0.0.1" in  https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/selenium/SeleniumStateMachine.kt   HomePage(chromeDriver).visit(callUrlInfo.baseUrl)  works  . Rebuild the jar and deploy

**Comment by agostinimarco** [comment]
> its seems that change the url from callUrlInfo.baseUrl to "http://127.0.0.1" in https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/selenium/SeleniumStateMachine.kt HomePage(chromeDriver).visit(callUrlInfo.baseUrl) works . Rebuild the jar and deploy

Same problem here. I tried your fix but without success.

These is the message in my /var/log/jitsi/jibri/log.0.txt
2020-03-31 21:57:05.674 SEVERE: [62] org.jitsi.jibri.selenium.JibriSelenium.run() An error occurred while joining the call: org.openqa.selenium.WebDriverException: <unknown>: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

All the service are started correctly, when I press the record button on jitsi meet on jibri server start google-chrome process.

**Comment by sharkme** [comment]
> > its seems that change the url from callUrlInfo.baseUrl to "http://127.0.0.1" in https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/selenium/SeleniumStateMachine.kt HomePage(chromeDriver).visit(callUrlInfo.baseUrl) works . Rebuild the jar and deploy
> 
> Same problem here. I tried your fix but without success.
> 
> These is the message in my /var/log/jitsi/jibri/log.0.txt
> 2020-03-31 21:57:05.674 SEVERE: [62] org.jitsi.jibri.selenium.JibriSelenium.run() An error occurred while joining the call: org.openqa.selenium.WebDriverException: : Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
> 
> All the service are started correctly, when I press the record button on jitsi meet on jibri server start google-chrome process.

Did you install in the VM? if you gonna have a domain，there were not so much issue

**Comment by sharkme** [comment]
> > its seems that change the url from callUrlInfo.baseUrl to "http://127.0.0.1" in https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/selenium/SeleniumStateMachine.kt HomePage(chromeDriver).visit(callUrlInfo.baseUrl) works . Rebuild the jar and deploy
> 
> Same problem here. I tried your fix but without success.
> 
> These is the message in my /var/log/jitsi/jibri/log.0.txt
> 2020-03-31 21:57:05.674 SEVERE: [62] org.jitsi.jibri.selenium.JibriSelenium.run() An error occurred while joining the call: org.openqa.selenium.WebDriverException: : Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
> 
> All the service are started correctly, when I press the record button on jitsi meet on jibri server start google-chrome process.

And can you show me your config in  
/etc/hosts 
which deploy the jibri

**Comment by sharkme** [comment]
add the chromeOption --ignore-certificate-errors  at https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/selenium/JibriSelenium.kt
 can also solve this problem like this
 logPrefs.enable(LogType.DRIVER, Level.ALL)
        chromeOptions.setCapability(CapabilityType.LOGGING_PREFS, logPrefs)
        chromeOptions.addArguments("--ignore-certificate-errors")//ADD
        chromeDriver = ChromeDriver(chromeDriverService, chromeOptions)
        chromeDriver.manage().timeouts().pageLoadTimeout(60, TimeUnit.SECONDS)

**Comment by agostinimarco** [comment]
> 
> 
> add the chromeOption --ignore-certificate-errors at https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/selenium/JibriSelenium.kt
> can also solve this problem like this
> logPrefs.enable(LogType.DRIVER, Level.ALL)
> chromeOptions.setCapability(CapabilityType.LOGGING_PREFS, logPrefs)
> chromeOptions.addArguments("--ignore-certificate-errors")//ADD
> chromeDriver = ChromeDriver(chromeDriverService, chromeOptions)
> chromeDriver.manage().timeouts().pageLoadTimeout(60, TimeUnit.SECONDS)

Yes.
These resolve my problem.

I have two separated server (one for jitsi and one for jibri) behind a NAT.
The jitsi server are behind a reverse proxy (nginx with LetsEncrypt certificate).
The jitsi server use a self-signed certificate and jibri (chrome part) fail when try to connect to jitsi meet.

I modified my /etc/hosts to resolv mi domain to internal ip of jitsi.

Thank you. For me problem resolved.

**Comment by TinNguyen331** [comment]
@agostinimarco 
I have change /etc/hosts to internal IP but it still now work. I cant complite jar to add chromeOptions.addArguments("--ignore-certificate-errors")//ADD
Can you share this jar for me ? by sending it to my email: tinnguyen331@gmail.com
Thank you verymuch

**Comment by agostinimarco** [comment]
> 
> 
> @agostinimarco
> I have change /etc/hosts to internal IP but it still now work. I cant complite jar to add chromeOptions.addArguments("--ignore-certificate-errors")//ADD
> Can you share this jar for me ? by sending it to my email: [tinnguyen331@gmail.com](mailto:tinnguyen331@gmail.com)
> Thank you verymuch

apt-get -y install openjdk-8-jdk
apt-get -y install maven
cd
git clone https://github.com/jitsi/jibri.git
cd jibri

... modify the source code !

mvn clean verify package
cp target/jibri-8.0-SNAPSHOT-jar-with-dependencies.jar /opt/jitsi/jibri/jibri.jar

**Comment by robvella** [comment]
I fixed these issues by making sure all references to hostnames refer to the public, SSL encrypted URL. when the headless chrome tries to contact the internal address, and the ssl cert is self signed or doesn't include the internal domain, it'll fail.

**Comment by agostinimarco** [comment]
Thank you. I'll try it in a few days.

**Comment by vglebov** [comment]
I use docker-jitsi-meet, there the host names are set by default and I decided not to change them.

Found a way to add Google Chrome parameter:

```bash
mv /usr/bin/google-chrome /usr/bin/google-chrome-orig

cat <<EOF >/usr/bin/google-chrome
#!/bin/bash

/usr/bin/google-chrome-orig --ignore-certificate-errors  \$@
EOF 

chmod +x /usr/bin/google-chrome
```

**Comment by madcrang** [comment]
Gret vglebov!!

now i have another probem:
GRAVE: [92] org.jitsi.jibri.api.xmpp.XmppApi.run() Error starting Jibri service : org.openqa.selenium.WebDriverException: unknown error: DevToolsActivePort file doesn't exist

**Comment by vglebov** [comment]
@madcrang try add  --disable-dev-shm-usage and --no-sandbox:

```bash
mv /usr/bin/google-chrome /usr/bin/google-chrome-orig

cat <<EOF >/usr/bin/google-chrome
#!/bin/bash

/usr/bin/google-chrome-orig --ignore-certificate-errors --disable-dev-shm-usage --no-sandbox \$@
EOF 

chmod +x /usr/bin/google-chrome
```

**Comment by madcrang** [comment]
Hi @vglebov 

I continius with the same problem.

My goolge-chrome fle:
n# cat google-chrome
#!/bin/bash

/usr/bin/google-chrome-orig --ignore-certificate-errors --disable-dev-shm-usage $@
root@quirino13:/usr/bin#



Error into log.0.txt file:
2020-04-21 11:14:33.922 GRAVE: [75] org.jitsi.jibri.selenium.JibriSelenium.run() An error occurred while joining the call: org.openqa.selenium.WebDriverException: <unknown>: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
  (Session info: chrome=81.0.4044.113)
  (Driver info: chromedriver=81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}),platform=Linux 4.4.0-177-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'quirino13', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-177-generic', java.version: '1.8.0_242'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 81.0.4044.69 (6813546031a4b..., userDataDir: /tmp/.com.google.Chrome.6ppC3i}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:41783}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 81.0.4044.113, webStorageEnabled: true, webauthn:virtualAuthenticators: true}
Session ID: 189cfda687352aa1a1fbd80c6bcf775b with stack:
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:480)
org.jitsi.jibri.selenium.JibriSelenium.setLocalStorageValues(JibriSelenium.kt:175)
org.jitsi.jibri.selenium.JibriSelenium.access$setLocalStorageValues(JibriSelenium.kt:112)
org.jitsi.jibri.selenium.JibriSelenium$joinCall$1.run(JibriSelenium.kt:255)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

2020-04-21 11:14:33.923 INFORMACIÓN: [75] org.jitsi.jibri.selenium.JibriSelenium.onSeleniumStateChange() Transitioning from state Starting up to Error: SESSION Failed to join call
2020-04-21 11:14:33.923 INFORMACIÓN: [75] org.jitsi.jibri.service.impl.FileRecordingJibriService.onServiceStateChange() File recording service transitioning from state Starting up to Error: SESSION Failed to join call
2020-04-21 11:14:33.923 INFORMACIÓN: [75] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Current service had an error, sending error iq <iq to='jibribrewery@internal.auth.video.test.notariado.org/focus' id='TInH9-66' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error'/></iq>
2020-04-21 11:14:33.924 DETALLADO: [75] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: stop:recording
2020-04-21 11:14:33.924 INFORMACIÓN: [75] org.jitsi.jibri.JibriManager.stopService() Stopping the current service
2020-04-21 11:14:33.924 INFORMACIÓN: [75] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Stopping capturer
                                                                                                                               


When recorder stop with failed error, my process continuos running:
jibri      2897  0.0  0.7 438372 58024 ?        S    11:14   0:00  \_ /opt/google/chrome/chrome --type=zygote --enable-logging --log-level=0 --user-data-dir=/tmp/.com.google.Chrome.6ppC3i
jibri      2898  0.0  0.0  26580  3760 ?        S    11:14   0:00  |   \_ /opt/google/chrome/nacl_helper
jibri      2901  0.0  0.1 438372 15960 ?        S    11:14   0:00  |   \_ /opt/google/chrome/chrome --type=zygote --enable-logging --log-level=0 --user-data-dir=/tmp/.com.google.Chrome.6ppC3i
jibri      2968  0.0  0.9 4735500 76416 ?       Sl   11:14   0:00  |       \_ /opt/google/chrome/chrome --type=renderer --autoplay-policy=no-user-gesture-required --enable-automation --enable-logging --disable-webrtc-apm-in-audio-service --log-level=0 --remote-debugging-port=0 --test-type=webdriver --use-fake-ui-for-media-stream --field-trial-handle=8275223652468452289,11187426960557145007,131072 --enable-blink-features=ShadowDOMV0 --lang=es --user-data-dir=/tmp/.com.google.Chrome.6ppC3i --extension-process --disable-client-side-phishing-detection --enable-auto-reload --num-raster-threads=2 --enable-main-frame-be
jibri      2998  0.0  1.1 4747824 93100 ?       Sl   11:14   0:00  |       \_ /opt/google/chrome/chrome --type=renderer --autoplay-policy=no-user-gesture-required --enable-automation --enable-logging --disable-webrtc-apm-in-audio-service --log-level=0 --remote-debugging-port=0 --test-type=webdriver --use-fake-ui-for-media-stream --field-trial-handle=8275223652468452289,11187426960557145007,131072 --disable-gpu-compositing --enable-blink-features=ShadowDOMV0 --lang=es --user-data-dir=/tmp/.com.google.Chrome.6ppC3i --disable-client-side-phishing-detection --enable-auto-reload --num-raster-threads=2 --enable-main-fr
jibri      3003  0.0  0.6 4727052 51064 ?       Sl   11:14   0:00  |       \_ /opt/google/chrome/chrome --type=renderer --autoplay-policy=no-user-gesture-required --enable-automation --enable-logging --disable-webrtc-apm-in-audio-service --log-level=0 --remote-debugging-port=0 --test-type=webdriver --use-fake-ui-for-media-stream --field-trial-handle=8275223652468452289,11187426960557145007,131072 --disable-gpu-compositing --enable-blink-features=ShadowDOMV0 --lang=es --user-data-dir=/tmp/.com.google.Chrome.6ppC3i --disable-client-side-phishing-detection --enable-auto-reload --num-raster-threads=2 --enable-main-fr
jibri      2923  0.0  0.8 482384 68780 ?        Sl   11:14   0:00  \_ /opt/google/chrome/chrome --type=utility --field-trial-handle=8275223652468452289,11187426960557145007,131072 --lang=es --service-sandbox-type=network --enable-logging --ignore-certificate-errors --log-level=0 --disable-webrtc-apm-in-audio-service --alsa-output-device=plug:amix --ignore-certificate-errors --user-data-dir=/tmp/.com.google.Chrome.6ppC3i --enable-logging --log-level=0 --shared-files
jibri      2988  0.0  1.0 482260 83152 ?        Sl   11:14   0:00  \_ /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=8275223652468452289,11187426960557145007,131072 --enable-logging --log-level=0 --user-data-dir=/tmp/.com.google.Chrome.6ppC3i --gpu-preferences=MAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAA= --use-gl=swiftshader-webgl --enable-logging --log-level=0 --shared-files
jibri      2990  0.0  0.1 432780 15832 ?        S    11:14   0:00      \_ /opt/google/chrome/chrome --type=broker

**Comment by madcrang** [comment]
Hi,

issue resolved!!

Scenari:
- Reverse Proxy - IP Pública Jitsi server. SSL certificate
- Jitsi Server with nginx port 80 - Ip local
- Jibir server - ip local

Access to https://meet.server.org  go to Reverse Proxy ad it send https to jitsi server, port 80.
Jibri connect by LAN to meet.server.org --> /etc/hosts ip local for jitsi server
Problem?? Jibri server connecto by port 5222 for local ip, but connection to https://meet.server.org, so, and it is the problem. I resolved problem with NAT OUTPUT to PUBLIC IP.
Now  recorders are ok.

Regards

**Comment by toanlv92** [comment]
> Hi,
> 
> issue resolved!!
> 
> Scenari:
> 
> * Reverse Proxy - IP Pública Jitsi server. SSL certificate
> * Jitsi Server with nginx port 80 - Ip local
> * Jibir server - ip local
> 
> Access to https://meet.server.org go to Reverse Proxy ad it send https to jitsi server, port 80.
> Jibri connect by LAN to meet.server.org --> /etc/hosts ip local for jitsi server
> Problem?? Jibri server connecto by port 5222 for local ip, but connection to https://meet.server.org, so, and it is the problem. I resolved problem with NAT OUTPUT to PUBLIC IP.
> Now recorders are ok.
> 
> Regards

Please share memo screenshot

**Comment by shubhamblue** [comment]
> I fixed these issues by making sure all references to hostnames refer to the public, SSL encrypted URL. when the headless chrome tries to contact the internal address, and the ssl cert is self signed or doesn't include the internal domain, it'll fail.

This fixed my issue. 
Thank you very much.

**Comment by anghelflorin** [comment]
> > I fixed these issues by making sure all references to hostnames refer to the public, SSL encrypted URL. when the headless chrome tries to contact the internal address, and the ssl cert is self signed or doesn't include the internal domain, it'll fail.
> 
> This fixed my issue.
> Thank you very much.

Can you please point the entries you modified to make it work? There's a bunch of them in .env but I'm not sure which one are supposed to remain internally used and which to point to the external URL ( https://mytestrecorde.whatever which is configured with Letsencrypt )

**Comment by samuel-larsson** [comment]
> I fixed these issues by making sure all references to hostnames refer to the public, SSL encrypted URL. when the headless chrome tries to contact the internal address, and the ssl cert is self signed or doesn't include the internal domain, it'll fail.

I have a wildcard certificate for *.jitsi.mydomain.com, but I still have the issue. I would not like to force Chrome to ignore certificate errors. Can you show which files and where you edited the hostnames?

**Comment by rogeriomq** [comment]
I solved to add **--igore-certificates-errors** and **--disable-dev-shm-usage** in **/etc/jitsi/jibri/jibri.conf**, chrome -> flags, in my server-dev-meet...
My jibri.conf, 

> chrome {
    // The flags which will be passed to chromium when launching
    // add --ignore-certificate-errors and --disable-dev-shm-usage when chrome error be cause invalid certificate.
    flags = [
      "--use-fake-ui-for-media-stream",
      "--start-maximized",
      "--kiosk",
      "--enabled",
      "--disable-infobars",
      "--autoplay-policy=no-user-gesture-required",
      "--ignore-certificate-errors",
      "--disable-dev-shm-usage"
    ]
  }

Verify 5222 port enable with `ufw status`

**Comment by zioalex** [comment]
> I solved to add **--igore-certificates-errors** and **--disable-dev-shm-usage** in **/etc/jitsi/jibri/jibri.conf**, chrome -> flags, in my server-dev-meet... My jibri.conf,
> 
> > chrome {
> > // The flags which will be passed to chromium when launching
> > // add --ignore-certificate-errors and --disable-dev-shm-usage when chrome error be cause invalid certificate.
> > flags = [
> > "--use-fake-ui-for-media-stream",
> > "--start-maximized",
> > "--kiosk",
> > "--enabled",
> > "--disable-infobars",
> > "--autoplay-policy=no-user-gesture-required",
> > "--ignore-certificate-errors",
> > "--disable-dev-shm-usage"
> > ]
> > }
> 
> Verify 5222 port enable with `ufw status`

Thanks this solved the self signed certificate problem!

**Comment by bigguo1** [comment]
如果未使用域名需在".env"中设置谷歌参数免认证
CHROMIUM_FLAGS=--ignore-certificate-errors,--disable-dev-shm-usage
