### ISSUE TITLE
Wrong Dockerfile

### ISSUE THREAD

**Issue by ghost** [jitsi/jibri#25]
When I build image, I have this error:
ERROR: unsatisfiable constraints:
  icewm (missing):
    required by: world[icewm]
The command 'apk add --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted icewm pulseaudio' returned a non-zero code: 1

Alpine remove icewm from alpine's repository:
https://pkgs.alpinelinux.org/packages?name=icewm&branch=&repo=&arch=&maintainer=

**Comment by xrnm** [comment]
I removed icewm from the Dockerfile and it build successfully. If a window manager is needed it looks like alpine is using xfce. so you can add this line

`RUN ["apk", "add", "xfce4"]`

I haven't not been successful with a jitsi integration yet, but I did manage to get the container to build and run.

**Comment by alfredogt** [comment]
Hi @xrnm 
Could you tell me how you are going with integration with jitsi-meet?
How did you manage to run it?

Thank you!

**Comment by raphaelkong** [comment]
Hi,
I've got the same issue than ghost.
It seems that the icewm package is no more available ?!

**Comment by aaronkvanmeerten** [comment]
Hi Jibri Fans,

I’m concerned about the desire to run Jibri within Docker.  Jibri requires certain kernel extensions to be made available to it, which Docker makes difficult to configure.  At the moment I do not suggest running Jibri in Docker.  

The existing Dockerfile was an attempt towards this goal, but Docker integration is not a real goal for Jibri given its close ties to the kernel module configuration.

Cheers,

-Aaron

**Comment by raphaelkong** [comment]
Hi !
Do you think we could find some documentation for the setup without docker ?

**Comment by saghul** [comment]
@aaronkvanmeerten I think we should remove it then, not to mislead others. Once / if we come up with a way to do it kosher we can bring it back. WDYT?

**Comment by aaronkvanmeerten** [comment]
Agreed, I’ll do that today.

-Aaron

**Comment by raphaelkong** [comment]
Thx for your help guys :]

**Comment by saghul** [comment]
The dockerfile is now gone and not supported, the README contains instructions on how to install Jibri.
