### ISSUE TITLE
Error trying to gracefully stop ffmpeg, destroying forcibly

### ISSUE THREAD

**Issue by gianogli** [jitsi/jibri#250]
## Description
---

I'm trying to record a meeting with jibri but the output mp4 file is corrupted:
```
~$ vlc 123_2020-03-20-16-12-05.mp4 
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
[0000560d743025b0] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7470c6da80] moov atom not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7400c11d00] moov atom not found
[00007f7400001180] avformat demux error: Could not open /home/pinco/123_2020-03-20-16-12-05.mp4: Unknown error 1094995529
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu
```

I think that the issue is related to this log:
```
2020-03-20 16:46:55.751 SEVERE: [87] org.jitsi.jibri.util.JibriSubprocess.ffmpeg.stop() Error trying to gracefully stop ffmpeg, destroying forcibly
```

The mp4 file is truncated, so for the player is corrupted.

## Current behavior
---

The mp4 output file is corrupted.
No error in /var/log/jitsi/jibri/ffmpeg* files

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---
1) Start a meeting.
2) Click on "Start Recording"
3) wait a while
4) Click on "Stop Recording"
No errors on the script but file corrupted

# Environment details
---
Ubuntu 18.04.4 LTS
jibri 8.0-14-g0ccc3f6-1
ffmpeg 7:3.4.6-0ubuntu0.18.04.1

**Comment by bbaldino** [comment]
Please attach all the logs

**Comment by gianogli** [comment]
Here the logs...
Thanks. :-)

[browser.0.txt](https://github.com/jitsi/jibri/files/4361062/browser.0.txt)
[log.0.txt](https://github.com/jitsi/jibri/files/4361063/log.0.txt)
[ffmpeg.0.txt](https://github.com/jitsi/jibri/files/4361065/ffmpeg.0.txt)

**Comment by bbaldino** [comment]
Which java version are you using?  Please make sure to use java 8...it looks like you may be using a later version.  That _might_ explain things, but not sure--it's not clear from the log, but I think the subprocess APIs changed between java versions.

**Comment by gianogli** [comment]
ii  java-common                           0.68ubuntu1~18.04.1 
ii  openjdk-11-jre-headless:amd64         11.0.6+10-1ubuntu1~18.04.1

**Comment by gianogli** [comment]
You are right, I'm using java 11... I'll try to install java 8 in the next hours...
Thanks

**Comment by gianogli** [comment]
I already tried.
With java 8 all is working as expected!
Thanks!!!!!

**Comment by ForgottenLight4415** [comment]
I'm facing exactly the same issue. Jibri does not even start the service with Java 8 in my case

**Comment by saghul** [comment]
We use Java 11 now, make sure you update.

**Comment by ForgottenLight4415** [comment]
I've recently installed jibri on my system. I'm using Java 11 and it gives me the said error that FFMPEG cannot be stopped gracefully. So as per many solutions I tried with adoptopenjdk-8 but with this, jibri service crashes right away. So now I'm literally stuck with this error.

**Comment by damencho** [comment]
What is the available RAM for jibri?

**Comment by ForgottenLight4415** [comment]
8 GB RAM 4 vCPUs
It's an AWS T2.large ec2 instance

**Comment by damencho** [comment]
Looks reasonable... Check ffmpeg logs, what is the coefficient shown there is it above or below 1?

**Comment by ForgottenLight4415** [comment]
how do I find that? I have the logs but how does this coefficient look like?

**Comment by ForgottenLight4415** [comment]
Hey! It turns out that I was somehow using Java 17 for Jibri, I have multiple JDK installed. Changed it to 11 and now it works as expected.
