### ISSUE TITLE
jibri recording & streaming failure

### ISSUE THREAD

**Issue by yodaphone** [jitsi/jibri#261]
First off, i really wish there was an updated tutorial or writeup to get Jibri working correctly.

1. The video tutorial says to use unstable build for jibri & stable for jitsi
2. its really not clear what version of Java should one use to get this going.
3. Will this work on Ubuntu 18.04 OR only in 16.04?
4. What version of Google Chrome / chromedriver to use?

I've been pulling my hair out to get this working for the past 4 days and after so many installs with different combinations it still doesnt work. The more frustrating part is that, no one from Jitsi is responding to questions in the Community.

So, please write a fresh & updated tutorial that we can use to get this up & running.

**Comment by bbaldino** [comment]
Sorry you're having a hard time.  We're doing our best to respond on the community but these are very hectic times for us, and community activity is also very high so there may be topics we miss.  Feel free to link to your community thread here, but that's the appropriate place for this so I'm going to close this bug.

**Comment by yodaphone** [comment]
this is the link to the thread

https://community.jitsi.org/t/solved-partially-jibri-recording-stucked-with-recording-has-stopped-then-busy/17783/19

**Comment by yodaphone** [comment]
hi, i reinstalled and still have the issue. can you please look at this post

https://community.jitsi.org/t/solved-partially-jibri-recording-stucked-with-recording-has-stopped-then-busy/17783/30?u=masteryoda

**Comment by yodaphone** [comment]
hi i updated your reply

**Comment by yodaphone** [comment]
this is my telnet output

telnet meet.mydomain.com 443
Trying 192.168.10.6...
Connected to meet.mydomain.com.
Escape character is '^]'.

**Comment by bbaldino** [comment]
Please stop commenting here, let's stick to the forum thread.
