### ISSUE TITLE
Jibri will not start and Jitsi does not find any Jibris

### ISSUE THREAD

**Issue by stevetoppenheim** [jitsi/jibri#265]
Hi Everyone,

I have posted on the community site without any responses or potential solution. This is why I post here.I suspect a problem with the jibri install docs which I am willing to assist and modify with more detail once I get things running stable with Jibri.

Situation: Jibri will not start and Jitsi does not find any Jibris.
I have successfully installed Jitsi and like many others I love it! Unfortunately after following the Jibri directions I have thus far been unsuccessful at getting my Jibri to run successfully.

Configuration:
I have a 2 server config:
Jitsi server: Ubuntu 18.04 3GB 90GB 4 processor java 1.8.0_242- worx great!
Jibri server: Ubuntu 16.04 2GB 50GB 2 processor java 1.8.0_242

domain: “opey.org”
jitsi domain instance: “jitsimeet.opey.org”

Over-all current arch:
Internet Clients <–> ISP Router <—> (jitsi & jibri svr) <–>FW <–> Router 2 <–> internal Client

End Goal: Move the 2 servers behind the “Router 2” NAT eventually after I get them working where they are…

Current Situation and Problem statement:
0/ On web page client front end: after choosing record: Recording unavailable
1/ Jitsi Server - works great, love it!
2/ Jibri server is configured but will not start and of course, Jitsi cannot find any jibris and I’m at a point of banging my head on the wall. I am guessing either I am not reading the documentation correctly or it needs to be revised in order to ensure a good Jibri install.

3/Jibri and jitsi server config and log files:

Jitsi and Jibri config files and logs: [LINK](https://www.dropbox.com/s/a73na53ll2vby1r/my-config.txt?dl=0)

Kind regards
Steve
---

## Current behavior:  Jitsi runs fine but does not find any Jibris.  Jibri fails to start appropriately.
---

## Expected Behavior: I expect Jibri to at least start
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by bbaldino** [comment]
You've got a lot of this in there:

org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'localhost:5222' failed because: localhost/127.0.0.1 exception: java.net.ConnectException: Connection refused (Connection refused), localhost/0:0:0:0:0:0:0:1 exception: java.net.ConnectException: Connection refused (Connection refused)

Can you start a thread on community.jitsi.org for this and we can continue it there?
