### ISSUE TITLE
Recording & Streaming simultaneously

### ISSUE THREAD

**Issue by yodaphone** [jitsi/jibri#271]
I have 1 jitsi & 2 jibris running. I've described my issue on the community forum & not had luck with responses. 

https://community.jitsi.org/t/stream-record-simultaneously-with-2-jibris/34809?u=masteryoda

jicofo logs see both the jibris but i'm unable to record & stream parallelly. they work independently with both jibris though

**Comment by bbaldino** [comment]
Please don't file an issue just because you don't get a response in the community, that's not what they're for.
