### ISSUE TITLE
apt-key add should not be used

### ISSUE THREAD

**Issue by 532910** [jitsi/jibri#272]
https://manpages.debian.org/buster/apt/apt-key.8.en.html says:

> **add**
> ...
> Note: Instead of using this command a keyring should be placed directly in the /etc/apt/trusted.gpg.d/ directory with a descriptive name and either "gpg" or "asc" as file extension.

Please update https://github.com/jitsi/jibri/blob/master/README.md

**Comment by thkoch2001** [comment]
I provided more information about the current best practice in https://github.com/CollaboraOnline/online/issues/1934, adapting it here:

The recommended way is:

1. Download the archive public key to `/usr/share/keyrings/$SOMENAME-archive-keyring.gpg`.
2. Adapt and add the following lines into `/etc/apt/sources.list.d/$SOMENAME.sources`:

```
Types: deb
URIs: $REPOURI
Suites: $SUITES
Signed-By: /usr/share/keyrings/$SOMENAME-archive-keyring.gpg
```

More documentation:

- https://wiki.debian.org/DebianRepository/UseThirdParty
- [man 5 sources.list](https://manpages.debian.org/buster/apt/sources.list.5.en.html) - for the not so common data sources file format

**Comment by damencho** [comment]
PRs are welcome, the https://jitsi.org/qi already are using this:

```
curl https://download.jitsi.org/jitsi-key.gpg.key | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/jitsi-keyring.gpg'
echo 'deb [signed-by=/usr/share/keyrings/jitsi-keyring.gpg] https://download.jitsi.org stable/' | sudo tee /etc/apt/sources.list.d/jitsi-stable.list > /dev/null
```

**Comment by damencho** [comment]
Is this ok? https://github.com/jitsi/jibri/pull/397
