### ISSUE TITLE
jibri and ubuntu bionic empty mp4 - java 11

### ISSUE THREAD

**Issue by verbavolant** [jitsi/jibri#274]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
jibri on ubuntu bionic, with java11, can't make a visible recording 

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---
install java8 and select as default

## Steps to reproduce
---

# Environment details
---

**Comment by bbaldino** [comment]
Jibri doesn't support running with Java 11, make sure to use Java 8.

**Comment by thyagopacher** [comment]
Any news on the subject? * I would like to keep JDK 11, but it is very good for me to have Jibri ...
I've been looking for some official documentation about the Jibri in Jitsi and I found nothing about it, just several comments mirrored in various and various forums
