### ISSUE TITLE
Failed to start Jibri Process.

### ISSUE THREAD

**Issue by toanlv92** [jitsi/jibri#279]
root@jitsi:~# systemctl status jibri
â jibri.service - Jibri Process
   Loaded: loaded (/etc/systemd/system/jibri.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-04-22 19:11:52 +07; 4s ago
  Process: 5585 ExecStop=/opt/jitsi/jibri/graceful_shutdown.sh (code=exited, status=7)
  Process: 5536 ExecStart=/opt/jitsi/jibri/launch.sh (code=exited, status=143)
 Main PID: 5536 (code=exited, status=143)

**Comment by bbaldino** [comment]
Please start a thread in the community forum and include Jibri logs.
