### ISSUE TITLE
Chrome is being controlled by automated software

### ISSUE THREAD

**Issue by jbrundige** [jitsi/jibri#289]
Hello!

All my Jibri recording have the "Chrome is being controlled by automated software info notice. 

I tried @dbkr 's solution:

/etc/opt/chrome/policies/managed/managed_policies.json with contents:

{
  "CommandLineFlagSecurityWarningsEnabled": false
}

 to this but I am running Chrome 81 and I think that's why it doesn't work. Anybody know how to disable this in Chrome 81? 

I found this solution:
ChromeOptions options = new ChromeOptions();
options.setExperimentalOption("useAutomationExtension", false);
options.setExperimentalOption("excludeSwitches",Collections.singletonList("enable-automation"));    
WebDriver driver = new ChromeDriver(options);

from this thread: https://www.edureka.co/community/145/notification-controlled-automated-software-chromedriver

but I have no idea how to implement ChromeOptions. Any ideas? 

Thank you!

_Originally posted by @jbrundige in https://github.com/jitsi/jibri/issues/208#issuecomment-624977432_

**Comment by jordanurbs** [comment]
Am also curious for a solution, I have the same issue...

**Comment by htcheng** [comment]
I also have the same issue - have tested this yet, but I think the solution might be found here: https://help.applitools.com/hc/en-us/articles/360007189411--Chrome-is-being-controlled-by-automated-test-software-notification

**Comment by jbrundige** [comment]
Woah, thank you so much! This is the solution I had been looking for!!

**Comment by htcheng** [comment]
FYI - I haven't tested it yet, but this looks like a solution for newer versions of Chrome:

https://community.jitsi.org/t/chrome-is-being-controlled-by-automated-software-message-at-recorded-video/52365
