### ISSUE TITLE
Does jibri create a playlist file?

### ISSUE THREAD

**Issue by yodaphone** [jitsi/jibri#292]
I came across an interesting blog post by matrix where they mentioned this

**"When you start streaming to your RTMP server, it will create a playlist file"**

https://matrix.org/docs/guides/running-online-events#configuring-the-live-stream

Does jibri create a playlist file & can we use this in a JS player like Google shaka?

this can actually make a webinar mode easy to do in jitsi/jibri

**Comment by bbaldino** [comment]
Jibri doesn't do this as far as I know (so unless ffmpeg is doing something automatically, I don't think so).  In the future, ask this sort of thing over at community.jitsi.org
