### ISSUE TITLE
custom option for chromedriver

### ISSUE THREAD

**Issue by stregouet** [jitsi/jibri#298]
Hi, 
first thanks for providing such a cool jitsi companion!
I have a special use case where I need to enable a chrome extension on startup, my best guess was to add `--load-extensions=/path/to/extension/folder` flag in `chromeOptions` variable. Do you have any other/better idea?
I will provide a pull request soon, I hope it will make easier to understand my point ;)

**Comment by bbaldino** [comment]
chrome options now configurable: https://github.com/jitsi/jibri/pull/327
