### ISSUE TITLE
preJoinPage cannot be used with Jibri

### ISSUE THREAD

**Issue by neimaravila** [jitsi/jibri#301]
## Description
preJoinPage cannot be used with Jibri
---

## Current behavior
With preJoinPage = true, cannot start 
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
enable preJoinPage on /etc/jitsi/meet/domain-config.js
---

# Environment details
debian 10 buster
---

**Comment by saghul** [comment]
This is fixed in master and will be part of the next release.
