### ISSUE TITLE
Configuring Jitsi Recording

### ISSUE THREAD

**Issue by jacq0123** [jitsi/jibri#31]
Hello,
We need help configuring the recording on Jitsi. I'm attaching a picture of how far we have reached. We need de directions on how to do it.
Thanks for looking into this. 
![screen shot 2017-03-15 at 6 42 43 am](https://cloud.githubusercontent.com/assets/26360432/23950277/d5f5209e-0960-11e7-83a0-a08830e8ebb7.png)

**Comment by krakatoa** [comment]
Please check that your Jitsi Meet configuration follows the settings specified here: https://github.com/jitsi/jibri#connecting-jibri-to-jitsi-meet

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian respository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
