### ISSUE TITLE
Debian dependencies

### ISSUE THREAD

**Issue by olaf7** [jitsi/jibri#312]
The Jibri .deb packages has a dependency on: default-jre-headless | java8-runtime-headle
ss | java8-runtime
Debian is very conservatives, yet Jibri wins. default-jre-headless in Debian Buster (stable) matches Java 11 which is way newer.
Jibri really needs Java8.
Preferred solution: rebuildPrefered/redistribution on something more modern: i.e Java-11
Workaround : add  https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ as a repository

Jibri needs Chrome/Chromedriver **or(!?) Chromium/Chromiumdriver** but these dependencies are not in the package its DEBIAN/control file. Chrome/Chromedriver are not packaged. Chromium/Chromiumdriver are.

**Comment by jbg** [comment]
I think this can be closed, Jibri works with Java 11 now.
