### ISSUE TITLE
Jibri startup options cannot be easily changed although required on Debian

### ISSUE THREAD

**Issue by olaf7** [jitsi/jibri#313]
Running Jibri Debian package on Debian stable (Buster).

Tweaks added to /etc/chromium.d/jibri are ignored and will be system-wide so it will influence not only jibri
Options are hardcoded: https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/selenium/JibriSelenium.kt
I would like to try options which could very well be solving my problem (see below) like: **disable-dev-shm-usage**
Defining options in a config file is much preferable to having them in an environment variable.
Without these extra options the Jibri Debian package is very unlikely to be able to function as intended.

Why?
org.jitsi.jibri.api.xmpp.XmppApi.run() Error starting Jibri service : org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

Related to bugs:

- https://github.com/jitsi/jibri/issues/303
- https://github.com/jitsi/jibri/issues/298
- Most likely others.

**Comment by jbg** [comment]
I think this can be closed now that there is the `jibri.chrome.flags` key in the config file?

**Comment by olaf7** [comment]
Great to hear, but where can I find the documentation on how and where(!) I can implement and test this? (where is this file located?)
I do see a file: https://github.com/jitsi/jibri/blob/master/src/main/resources/reference.conf
and I do have an more or less empty: /etc/jitsi/jibri/jibri.conf which probably has a similar markup as above file.
But `jibri.chrome.flags` is a different layout of configuration.

**Comment by bbaldino** [comment]
You can override the `jibri.chrome.flags` in the `jibri.conf` file using the same syntax that's in `reference.conf`
