### ISSUE TITLE
No Jibri Instance Available

### ISSUE THREAD

**Issue by thangasblockchain** [jitsi/jibri#318]
*This Issue is regarding config of jitsi and jibri on same server.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
I have setup My Jitsi server and Jibri on Same instance (AWS EC2).
My Jitsi is running Fine,
But when I click record, It is throwing Issue (No JIbri Instance Available)
 I have followed this -> https://www.youtube.com/watch?v=S43-A1N_COE&t=1405s 

## Current behavior

<img width="1429" alt="Screenshot 2020-07-10 at 10 42 27 AM" src="https://user-images.githubusercontent.com/40734900/87122931-6fd66200-c2a3-11ea-817b-a413fefba85d.png">

## Log details

https://pastebin.com/z8wfV0Mv

Facing this issue for quite sometime, Kindly help me out. Thanks in advance.

# Environment details
---

**Comment by bbaldino** [comment]
Please start a thread on community.jitsi.org
