### ISSUE TITLE
Allow jibri to record no sound and/or no video user

### ISSUE THREAD

**Issue by cesarcorzo** [jitsi/jibri#320]
There is an scenario where a user with **no video** and **no sound** creates and starts a conference recording. When a second user with audio and/or video joins the conference, jibri breaks the recording with Error: SESSION No media received. I set my config.json with “usage_timeout”:“0” but to no avail.

If a user with no video and no sound starts a conference recording and it is the only user (no other user joins) Jibri does not break and keeps recording.

**Comment by bbaldino** [comment]
This timeout isn't based on `usage_timeout`, it's from [NO_MEDIA_TIMEOUT](https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/selenium/status_checks/MediaReceivedStatusCheck.kt#L57) which is 30 seconds (and not currently configurable, but you could change it and rebuild).

**Comment by bbaldino** [comment]
> If a user with no video and no sound starts a conference recording and it is the only user (no other user joins) Jibri does not break and keeps recording.

This is surprisingly and shou

**Comment by cesarcorzo** [comment]
> This timeout isn't based on `usage_timeout`, it's from [NO_MEDIA_TIMEOUT](https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/selenium/status_checks/MediaReceivedStatusCheck.kt#L57) which is 30 seconds (and not currently configurable, but you could change it and rebuild).
Is there a way to make it configurable?  

Thanks for the prompt response.

**Comment by bbaldino** [comment]
So I think you might be seeing what I described [here](https://community.jitsi.org/t/jibri-live-streaming-stopped-when-unmuting-after-2-mins/71290/9).  Can you confirm if that sounds right?  If so I'll change the description of this bug and use this one.

**Comment by cesarcorzo** [comment]
Yup. That sounds right. Would that fix the issue when a user doesn't send audio nor video?

**Comment by bbaldino** [comment]
If all users are muted, then Jibri waits 10 minutes before timing out.

**Comment by bbaldino** [comment]
Fixed by https://github.com/jitsi/jibri/pull/322
