### ISSUE TITLE
Moving Jibri Selenium status checks constants to an external config file

### ISSUE THREAD

**Issue by zWaR** [jitsi/jibri#325]
Hi @bbaldino,

We are really excited about Jibri and the awesome functionality it is providing. With our adoption of the project, we'd benefit from moving some of the constants, which control the behavior of Jibri Selenium status checks to an external config file. 

We are working on an application which utilizes jibri and is controlling it through the HTTP API. We'd like to implement the conference status checks in our application, but at the same time we still want to keep the existing functionality of Jibri and use its status checks as a fail-save. Therefore, it would be great if fine tuning Jibri configuration would not require building and maintaining a fork. We are willing to contribute the code, but we wonder if you would consider merging this kind of change into master?

Specifically, those are the constants we are considering to move to an external config:
* NO_MEDIA_TIMEOUT
* ALL_MUTED_TIMEOUT
* DEFAULT_CALL_EMPTY_TIMEOUT

Thank you very much!

**Comment by bbaldino** [comment]
Good news for you...I'm currently refactoring the config in Jibri which will make it very easy to make these settings configurable.  Also, I'm planning on improving the HTTP API in the near future as well.  You can track the config refactor [here](https://github.com/jitsi/jibri/pull/324).

**Comment by zWaR** [comment]
@bbaldino That's amazing, very excited about those changes!! Do you by any chance have an ETA for those new features?

Thanks so much.

**Comment by bbaldino** [comment]
Config refactor should be in the next week.  Don't have a timeline on the HTTP stuff.  Any particular pain points you've had with the current HTTP API?

**Comment by zWaR** [comment]
Hi @bbaldino,

Wow, this is fantastic, having the config next week would be amazing.  Thanks for asking about the HTTP API.

Some suggestions on HTTP API additions:
- One thing, we would definitely benefit from is an HTTP webhook for health, which would send a request to our application on a health status change (I know, this might be stretching it a little 😄  ).
- Another thing that we'd benefit from is additional data in the health entry point response, which would give us more information in cases when Jibri was unable to successfully connect to a conference. For example, this sort of information could be exposed: All participants muted, no video stream detected, call empty, ffmpeg errors. I can imagine this could be an enum of states that are returned in the response body (similarly to what you already are returning). I can imagine this kind of functionality is easier to implement as a webhook 😅 

Thank you very much for asking for suggestions!

**Comment by bbaldino** [comment]
> One thing, we would definitely benefit from is an HTTP webhook for health, which would send a request to our application on a health status change (I know, this might be stretching it a little 😄  ).

This is your lucky week, I guess :) A webhook for health went in recently: https://github.com/jitsi/jibri/pull/315.  Note that the implementation and config of this may change a bit.  It's not exactly a traditional webhook, but there is some documentation included in that PR.  I also have a branch in progress to enable JWT for the webhook requests.

> Another thing that we'd benefit from is additional data in the health entry point response, which would give us more information in cases when Jibri was unable to successfully connect to a conference. For example, this sort of information could be exposed: All participants muted, no video stream detected, call empty, ffmpeg errors. I can imagine this could be an enum of states that are returned in the response body (similarly to what you already are returning). I can imagine this kind of functionality is easier to implement as a webhook

This would probably come somewhere along the HTTP refactor--in general we currently have no way of pushing updates about a particular session in the HTTP API (short of health), so the plan would be to do something there.

**Comment by zWaR** [comment]
Hi @bbaldino,

Thanks so much for your hard work and those enhancements to the code.

We got a question for you. After the merge for #324 we do not notice a config option which would allow us to set customized values for the above mentioned constants. Are you planning to add that still or were you just saying we could add the customizations after #324 is finished.

Thanks!

**Comment by bbaldino** [comment]
> Hi @bbaldino,
> 
> Thanks so much for your hard work and those enhancements to the code.
> 
> We got a question for you. After the merge for #324 we do not notice a config option which would allow us to set customized values for the above mentioned constants. Are you planning to add that still or were you just saying we could add the customizations after #324 is finished.
> 
> Thanks!

I looked at doing those a while back but hit a bit of a snag...I think it was because the values are different for different services and I stopped to think how I wanted to do that and haven't gotten back to it yet.

**Comment by zWaR** [comment]
Hi @bbaldino,

we opened a Pull Request #335 which adds support for setting the above mentioned constants from a configuration file:
- NO_MEDIA_TIMEOUT
- ALL_MUTED_TIMEOUT
- DEFAULT_CALL_EMPTY_TIMEOUT

Thanks!

**Comment by zWaR** [comment]
Since this was merged with master in #335, I'll close this ticket.
