### ISSUE TITLE
Inactive users thumbnails in the filmstrip mode

### ISSUE THREAD

**Issue by crprata** [jitsi/jibri#326]
## Description
When I use jibri and filmstrip mode, the participants appear as inactive. When I change the title view to grid, it returns to normal. This happens intermittently several times.
I suppose that it's a bug. I think it's related to:
https://community.jitsi.org/t/videostream-stopps-and-goes-to-connection-status-inactive/36981
https://github.com/jitsi/jitsi-meet/issues/7227

The same behavior happens using meet.jit.si (https://prnt.sc/tb96jn).

## Steps to reproduce
1. Access https://meet.jit.si
2. Stay in a room with at least one more one person using filmstrip view. Start a live streaming.
3. After a few minutes, all participants change to inactive status.
4. If you change to the grid view, it returns to normal.

# Environment details
Latest stable Jibri and Jitsi versions.

**Comment by bbaldino** [comment]
If so, this would be a [jitsi meet](https://github.com/jitsi/jitsi-meet) bug, not Jibri.

**Comment by crprata** [comment]
@bbaldino Even if it doesn't happen to me that I'm in the jitsi room, on the streaming by Jibri, the users keep blinking alternating between inactive users. Wouldn't it be a Jibri configuration to save bandwidth that is being activated incorrectly?

**Comment by bbaldino** [comment]
I don't know--it's possible it's a legitimate network issue.  I would start a thread with details over on community.jitsi.org and we can go from there.
