### ISSUE TITLE
Jibri deb files release cycle

### ISSUE THREAD

**Issue by zWaR** [jitsi/jibri#333]
Hi everyone,

Thanks very much for your hard work on this project.

We were wondering what's the ETA for publishing the next jibri deb file with the latest code changes (https://download.jitsi.org/stable/)? What is the release cycle in general for deb installation files?

We are not sure if this is the correct place to ask this question. If it's not, please direct us where we should rather ask this.

Thank you very much!

**Comment by bbaldino** [comment]
Yeah I don't think we've done a stable release yet as we wanted more bake time.  You can download the unstable version though to try.

**Comment by bbaldino** [comment]
Btw, in the future things like this should go on community.jitsi.org
