### ISSUE TITLE
Ffmpeg quit abruptly.  Last output line: plug:bsnoop: Input/output error

### ISSUE THREAD

**Issue by akalana** [jitsi/jibri#345]
I did the setup of Jibri in an AWS Ubuntu 18.04 server. Did the work after adding your config file and it worked accurately. My issue is, in that instance, I entered an AMI. But it occurs an FFmpeg error in the AMI added Jibri. Have you got any ideas on this matter?

![image](https://user-images.githubusercontent.com/20404273/94331294-f53afa00-ffe8-11ea-9b8d-482da17786a7.png)

**Comment by bbaldino** [comment]
There's some issue with your device, I don't know if it's on the config side or the device setup side.  If you provide your config and show the created devices (with owners/permissions) we can probably figure it out.  But please start a thread on the community for this.
