### ISSUE TITLE
Jibri can't join room after jicofo changed to client_proxy and removed focus component

### ISSUE THREAD

**Issue by billybobilly** [jitsi/jibri#370]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

## Current behavior
Jibri fails to join room

## Expected Behavior
when jibri starts, chrome launches and joins the room

## Possible Solution
modify jibri to use client_proxy for focus like jicofo does now

## Steps to reproduce
connect a jibri instance to a prosody configured with focus as client_proxy and without focus component.  Start recording.

# Environment details
Linux Ubuntu 20

Log from jibri:
[jibri.log](https://github.com/jitsi/jibri/files/5938206/jibri.log)

**Comment by damencho** [comment]
Can you open 3 tabs in the browser on the same deployment?

**Comment by billybobilly** [comment]
Yes.  The deployment is working with 3+ users in the same room.  The jibri instance I'm trying to connect is also a working instance when it is connected to a jitsi that was installed by .deb packages (uses component connection for jicofo).

What I am trying to do is change the connection details on a working jibri instance so that it points to this new build that was done from source and uses the new client_proxy connection for jicofo

**Comment by billybobilly** [comment]
This jibri instance is also a jibri sip gateway connecting to PolyCom video calls and it works fine on the other .deb build.

**Comment by bgrozev** [comment]
Can you provide logs from jicofo and jibri when the failure occurs?

**Comment by billybobilly** [comment]
reivsed log with jibri and jicofo during the failure
[jibri-jicofo.log](https://github.com/jitsi/jibri/files/5939196/jibri-jicofo.log)

**Comment by damencho** [comment]
RemoteWebDriver.get(RemoteWebDriver.java:271)
WebDriverException: unknown error: net::ERR_CONNECTION_REFUSED

This means jibri cannot open the link of your deployment ... not sure what link it tries to open though ...

**Comment by billybobilly** [comment]
all ports are open to the server.  if it's chrome, it is just trying to open the browser to the room, right?  I am able to curl to the front end web server successfully from the command line on the recorder (jibri)

**Comment by billybobilly** [comment]
just watched the web server logs and see that the jibri makes a successful POST with a 200 response when it tries to connect.

**Comment by damencho** [comment]
It is interesting to see what's in there ...

**Comment by bgrozev** [comment]
Prior to the `Sending 'pending' response to start IQ` log in jibri do you see `Parsed call url`? Does the URL look correct?

**Comment by bbaldino** [comment]
Can you include the entire Jibri log please?

**Comment by billybobilly** [comment]
I'm creating a clean one for jibri and jicofo and prosody.  One minute

**Comment by billybobilly** [comment]
[log.0.txt](https://github.com/jitsi/jibri/files/5945902/log.0.txt)
[cofo.log](https://github.com/jitsi/jibri/files/5945903/cofo.log)
[prosody.log](https://github.com/jitsi/jibri/files/5945904/prosody.log)

**Comment by bbaldino** [comment]
Ok, and the `https://signal.xxxxxxx.xxx, callName=siptest` is correct for your environment?  Are you sure the Jibri machine is able to reach that url correctly?  Network connectivity, certs, etc. are all good?  Can you login to the Jibri and verify it?  (via curl or something)

**Comment by billybobilly** [comment]
signal.xxx is the prosody and jicofo server.  meet.xxxx is the web front end.  two separate servers.  meet.xxx works fine and is connected to signal with no problems.  Also, you can see from the logs that jibri is successfully connecting to the muc on signal.  

curl from jibri to https://meet.xxx gets the expected result and valid config:
 <script>/* eslint-disable no-unused-vars, no-var */

var config = {
    // Connection
    //

    hosts: {
        // XMPP domain.
....

telnet from jibri to signal on port 5222 connects successfully.

I'm looking into the certificates now, but what is confusing is that if I can get several participants in the same room with the web front end, why would the recorder not be able to join too?

**Comment by billybobilly** [comment]
just found that ...
Parsed call url info: CallUrlInfo(baseUrl=https://signal.xxxxxxx.xxx, callName=siptest, urlParams=[])
where is it gettin gthat for the call url?

**Comment by bbaldino** [comment]
https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/util/XmppUtils.kt#L28

**Comment by billybobilly** [comment]
so it is using the xmpp host as the default call url?
   else -> CallUrlInfo("https://$xmppDomain/$subdomain", callName)

Is this callurl supposed to the the XMPP server or is it the meeting url on the meet front end server?

**Comment by billybobilly** [comment]
That solved it.  NOT a problem related to client_proxy.  Sorry for the mis-direction.  Having the front end and signalling on different hosts was the issue.

**Comment by bbaldino** [comment]
Call URL should be the URL for the browser...for us those two things are always the same so we derive one from the other.  Jibri doesn't currently handle them being different.

**Comment by bbaldino** [comment]
> That solved it. NOT a problem related to client_proxy. Sorry for the mis-direction. Having the front end and signalling on different hosts was the issue.

Cool, ok glad you got it sorted.

**Comment by billybobilly** [comment]
Thank you for helping me through this!
