### ISSUE TITLE
Cannot start test ffmpeg

### ISSUE THREAD

**Issue by subsub** [jitsi/jibri#38]
I try to run ./start-ffmpeg.sh from scripts folder, but I get nothing.
When I check the `/tmp/jibri-ffmpeg.out` this is the log. Can you help?
```
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_6$
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, x11grab, from ':0.0+0,0':
  Duration: N/A, start: 1496036935.191281, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1280x720, 30 fps, 30 tbr, 1000k tbn, 30 tbc
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
[alsa @ 0x24ba1c0] cannot open audio device hw:0,1,0 (No such file or directory)
hw:0,1,0: Input/output error
```

**Comment by saghul** [comment]
> ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
> [alsa @ 0x24ba1c0] cannot open audio device hw:0,1,0 (No such file or directory)

Did you setup the ALSA loopback devices correctly?

**Comment by subsub** [comment]
@saghul I did like what it says in the readme. Here's the output when I check:
```
root@ubuntu:~# lsmod | grep snd_aloop
snd_aloop              24576  0
snd_pcm               106496  1 snd_aloop
snd                    81920  3 snd_aloop,snd_timer,snd_pcm
```

**Comment by saghul** [comment]
@subsub Did you copy the asoundrc file to the user's home directory? (I guess you need to restart ALSA afterwards).

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian respository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
