### ISSUE TITLE
Please clarify if chromium can be used instead of chrome

### ISSUE THREAD

**Issue by thkoch2001** [jitsi/jibri#409]
I'd very much prefer not to hand over my server to Google. Thus can I also run jibri with chromium instead of chrome? If there is no disadvantage, could you please change the installation instructions to recommend chromium over chrome?

**Comment by rutvora** [comment]
Hey, I was trying to build jibri docker for ARM64 and had to use chromium (no chrome on ARM64). It seems to be working fine.
The only problem I observed was that when I set the resolution to something less than 1920*1080 in the conf file, it cropped the video instead of decreasing size.
And there was a warning saying something like 'chromium is running in automated mode'

Although I assume both of these are not chromium specific problems and rather jibri's calls to ffmpeg and chromium/chrome
Not sure though

**Comment by xeruf** [comment]
Didn't you have to change some flags somewhere? What about chromedriver?

**Comment by jbg** [comment]
No need to change anything if your distro installs chromium's chromedriver as `chromedriver` (e.g. [Alpine does](https://pkgs.alpinelinux.org/contents?branch=edge&name=chromium-chromedriver&arch=aarch64&repo=community)). Sometimes it's called `chromiumdriver`, in which case you can make a symlink.

**Comment by saghul** [comment]
I forgot this one was open!

In fact we use Chromium in our arm64 Docker images: https://github.com/jitsi/docker-jitsi-meet/blob/master/jibri/rootfs/usr/bin/install-chrome.sh

Debian provides a working driver.

One detail to note is the policy for not showing the automation banner is located in a different directory, check the Docker ima for more details.

**Comment by dengzihaohs** [comment]
> I forgot this one was open!
> 
> In fact we use Chromium in our arm64 Docker images: https://github.com/jitsi/docker-jitsi-meet/blob/master/jibri/rootfs/usr/bin/install-chrome.sh
> 
> Debian provides a working driver.
> 
> One detail to note is the policy for not showing the automation banner is located in a different directory, check the Docker ima for more details.

Hi,Why do I execute the chrome -- version or chromedriver --version command to output Trace/breakpoint trap (core dumped). Are there any additional configurations？I‘m in arm64 docker image.

**Comment by saghul** [comment]
I don't know. Our docker images work on arm64 just fine.

**Comment by dengzihaohs** [comment]
> I don't know. Our docker images work on arm64 just fine.

What version of Debian are you using? 10 or 11

**Comment by saghul** [comment]
10.

**Comment by dengzihaohs** [comment]
> 

Is there an image of arm64 based on Debian10's jitsi/base-java on Dockerhub?

**Comment by saghul** [comment]
Yes the jitsi/jibri image
