### ISSUE TITLE
White Video Track on Jibri

### ISSUE THREAD

**Issue by jbrundige** [jitsi/jibri#412]
Hello, 

We have always intermittently had an issue where Jibri records audio, but only white for the video track. It used to happen so rarely that it wasn't an issue, but as our jibris have begun to get more use it is more on an issue. I have attached a sample video with a white video track. Has anyone else encountered this issue and know of a fix? Thank you

https://user-images.githubusercontent.com/54994646/121392697-7b436a80-c904-11eb-8207-9e5e4e8c34bf.mp4

**Comment by bbaldino** [comment]
Have you started a thread on community.jitsi.org?  Please do so there before opening a bug.  Include all Jibri logs as well.

**Comment by jbrundige** [comment]
sorry @bbaldino . I will post it there.
