### ISSUE TITLE
XmppCredentials writes passwords to logs

### ISSUE THREAD

**Issue by filippog** [jitsi/jibri#427]
## Description
---

Thank you for your work on Jibri!
While browsing its logs I noticed lines with `XmppCredentials` will have passwords in plaintext. AFAICT when leaked such credentials allow to join any jitsi room with the same privileges of jibri (e.g. unannounced)

## Current behavior
---
Credentials leaked to logs

## Expected Behavior
---
Passwords are redacted before logging

## Possible Solution
---
Passwords are redacted before logging

## Steps to reproduce
---
Observe jibri logs

**Comment by saghul** [comment]
@filippog Thanks for the report!

@oanaianc Can you please take a look?

**Comment by oanaianc** [comment]
Here is the fix for it https://github.com/jitsi/jibri/commit/9871ba137cb759d22d31e5e1f7cfade8e8b4ca65
