### ISSUE TITLE
live streaming no video and audio

### ISSUE THREAD

**Issue by akbarazimifar** [jitsi/jibri#436]
Hi

No video or audio is streamed during live video conferencing.

please guide me

Image attached
![jitsi](https://user-images.githubusercontent.com/5562558/131843097-342aded9-b314-453b-8233-b42435376fda.jpg)

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

https://community.jitsi.org/t/not-audio-and-only-grey-video/104774/2?u=damencho

**Comment by akbarazimifar** [comment]
I'm sorry . Thanks for the tips
