### ISSUE TITLE
start streaming ?

### ISSUE THREAD

**Issue by tkd4444** [jitsi/jibri#44]
Hi !

I was trying to adjust the jibri to stream to Facebook.

I have changed the following parameters at the `launch_recording.sh`

```
#!/bin/bash

URL=$1
STREAM=$2
TOKEN=$3
YOUTUBE_STREAM_ID=$4


export DISPLAY=:0

xdotool mousemove 1280 0

YOUTUBE_BASE="rtmp://rtmp-api.facebook.com/rtmp"

if [ ! -z "$5" ]; then
     YOUTUBE_BASE="rtmp://rtmp-api.facebook.com/rtmp"
fi

if [ ! -z "$4" ]; then
    STREAM="${YOUTUBE_BASE}/${YOUTUBE_STREAM_ID}"

    if [ ! -z "$5" ]; then
        STREAM="${STREAM}?backup=1"
    fi
fi

./start-ffmpeg.sh $STREAM
```

When I launch it via 

`./launch_recording.sh null null null FB_STREAM_KEY`

It connects to FB and there is the connecting.png showing up so it works.

However, when I launch it via jitsi-meet it doesnt want to connect, I'm wondering is there any hard written youtube_rtmp URL written somewhere which I missed ?

Thanks a lot !

**Comment by tkd4444** [comment]
Streaming to youtube works fine and since FB uses the rtmp I thought I make it work.

**Comment by tkd4444** [comment]
Any suggestions ? @damencho

**Comment by harvlad** [comment]
+1

**Comment by nightstryke** [comment]
Anyone have any idea on how to set this up to use your own rtmp server?

**Comment by aaronkvanmeerten** [comment]
You would need to override the shell scripts in /scripts to point to your own URL.  Right now the script launch_recording.sh defines a YOUTUBE_BASE which you could change to point to any rtmp URL as long as it fits the same scheme as youtube.

**Comment by tkd4444** [comment]
@aaronkvanmeerten I have tried this, it's not working. It opens the RTMP stream to youtube, but the video doesn't go thru.

**Comment by nightstryke** [comment]
@tkd4444 At least you can get that far, my jibri doesn't even want to stream to youtube and says it's unavailable.

**Comment by aaronkvanmeerten** [comment]
It may be that the ffmpeg settings that work for youtube are slightly different from facebook.  You may look at tuning the ffmpeg command by hand first.  Part of the reason these are all shell scripts is to allow for testing/tuning outside the jibri daemon itself.  Best success is found when you can first test each piece separately before combining them.  In this case, my suggestion is to attempt to stream to facebook using ffmpeg and see if you can get a blank desktop to show up in facebook.  If so, then you are on the right track and can go back to launching it through jibri and see if anything changes.

Let me know if you find success, and we can look at integrating your changes into the open source scripts.

**Comment by krisalay** [comment]
@aaronkvanmeerten 
Hi,
I have managed to get the pop up to enter the youtube stream key. I entered my youtube live stream key. Then I click on "Start Live Streaming", its shows "starting live stream". It stays like this for few minutes and then I get "Live stream failed to start".

The log for my jibri-xmpp is:
`Mar 25 14:30:17 ubuntu-xenial app.py[1863]: 2018-03-25 14:30:17,531 INFO      * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)`
`Mar 25 14:30:17 ubuntu-xenial app.py[1863]: 2018-03-25 14:30:17,532 INFO     jibri_watcher starting up...`
`Mar 25 14:30:18 ubuntu-xenial app.py[1863]: 2018-03-25 14:30:18,095 INFO     Negotiating TLS`
`Mar 25 14:30:18 ubuntu-xenial app.py[1863]: 2018-03-25 14:30:18,097 INFO     Using SSL version: TLS 1.0`
`Mar 25 14:30:18 ubuntu-xenial app.py[1863]: 2018-03-25 14:30:18,420 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED.`
`Mar 25 14:30:19 ubuntu-xenial app.py[1863]: 2018-03-25 14:30:19,499 INFO     JID set to: jibri@auth.meet-07.talview.com/3bfd9b10-9bd2-4818-985a-fda83b7ab25c`
`Mar 25 14:30:19 ubuntu-xenial app.py[1863]: 2018-03-25 14:30:19,660 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED.`
`Mar 25 14:30:19 ubuntu-xenial app.py[1863]: 2018-03-25 14:30:19,662 INFO     Starting up client <jibrixmppclient.JibriXMPPClient object at 0x7f548be83748>, connecting t`
`Mar 25 14:30:19 ubuntu-xenial app.py[1863]: 2018-03-25 14:30:19,820 INFO     sending presence: <presence xml:lang="en" to="TheBrewery@conference.meet-07.talview.com"><j`
`Mar 25 14:30:19 ubuntu-xenial app.py[1863]: 2018-03-25 14:30:19,823 INFO     Started up client <jibrixmppclient.JibriXMPPClient object at 0x7f548be83748>`

Can you please tell me how to get the live stream started?

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian respository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
