### ISSUE TITLE
Live Streaming Service is Currently Unavailable

### ISSUE THREAD

**Issue by nightstryke** [jitsi/jibri#46]
So I followed the directions on install right down to the letter, but I keep getting this when I load jitsi-meet up. "Live Streaming Service is Currently Unavailable. Please try again later."

**Comment by nightstryke** [comment]
Ok so I've searched everything and this is what's my problem
`Oct 09 16:15:30 hangout app.py[1061]: 2017-10-09 16:15:30,907 ERROR    Could not match certficate against hostname: hangout.mydomain.org`
`Oct 09 16:15:30 hangout app.py[1061]: 2017-10-09 16:15:30,908 WARNING  Failed to send b"<stream:stream to='hangout.mydomain.org' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client'`
`Oct 09 16:15:30 hangout app.py[1061]: 2017-10-09 16:15:30,908 ERROR    Socket Error #9: Bad file descriptor`

**Comment by aaronkvanmeerten** [comment]
This looks like an issue with the SSL certificates used by prosody.  There is a known issue here, and my workaround for now is to NOT have the proper SSL verification libraries installed (py_asn1).  That way, no SSL verification occurs.  Alternately, ensure that the prosody installation has the appropriate SSL certificates to allow for full chain verification.  There is an open PR against jitsi-meet currently which fixes this SSL issue, so a newer version of jitsi-meet with a new installation may also help resolve this once that PR is merged.

**Comment by nightstryke** [comment]
I've been working on this for days, weeks and it's driving me insane. How would I go about uninstalling py_asn1 and it's associated modules?

**Comment by aaronkvanmeerten** [comment]
If you're on ubuntu and installed from packages:
http://installion.co.uk/ubuntu/xenial/main/p/python-pyasn1-modules/uninstall/index.html

If you're using pip you can just say:
pip uninstall pyasn1-modules

I misspoke earlier, pyasn1 is required, but pyasn1-modules is the culprit here.

**Comment by nightstryke** [comment]
Alright did that, but I'm still getting the "Live Streaming Service is Currently Unavailable. Please try again later." error.

**Comment by aaronkvanmeerten** [comment]
So the next place to look here will be in the Jicofo logs.  The way jibri works is, it joins a MUC on the prosody server, and then jicofo looks to find a jibri in the MUC.  Jicofo must be configured to look for the jibris, like so:

Jicofo 2017-10-03 02:10:46.409 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.jicofo.jibri.BREWERY=TheBrewery@YOURMUCSERVER.YOURDOMAIN

If jicofo finds one, log lines will be printed like so:

Jicofo 2017-10-03 02:12:39.109 INFO: [36] org.jitsi.jicofo.xmpp.BaseBrewery.processInstanceStatusChanged().296 Added brewery instance: jibribrewery@YOURMUCSERVER.YOURDOMAIN/jibri-6789373949489196
Jicofo 2017-10-03 02:12:39.110 INFO: [36] org.jitsi.jicofo.recording.jibri.JibriDetector.notifyJibriStatus().168 Jibri: thebrewery@YOURMUCSERVER.YOURDOMAIN/jibri-6789373949489196 available: true


If this occurs, then Jicofo will send a presence out to the clients.

Jicofo 2017-10-03 02:21:12.190 INFO: [38] org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Publish new JIBRI status: <jibri-recording-status xmlns='http://jitsi.org/protocol/jibri' status='off'/> in: torture936623@conference.jitsi.net

This presence is also visible in the console log of your browser, and should show that the jibri status moves from unavailable to off.

If you are missing any of this, then you will see the LIve Streaming not available.  Can you check your jicofo logs and see whether this is present?

**Comment by nightstryke** [comment]
Jicofo 2017-10-10 11:22:41.469 WARNING: [36] org.jitsi.impl.protocol.xmpp.ChatRoomImpl.processOtherPresence().1369 Presence for not existing member: <presence to="focus@auth.hangout.mydomain.org/focus24541710229" from="test@conference.hangout.mydomain.org/af403c74">
<user-agent xmlns="http://jitsi.org/jitmeet/user-agent"></user-agent><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://jitsi.org/jitsimeet' ver='bInwKC/7Lt0uq2Y1/f66QQKgRS4='/><devices xmlns="jabber:client"><audio>true</audio><video>true</video>
</devices><email xmlns="jabber:client"></email><nick xmlns="http://jabber.org/protocol/nick">nightstryke</nick><audiomuted xmlns="http://jitsi.org/jitmeet/audio"></audiomuted><videoType xmlns="http://jitsi.org/jitmeet/video"></videoType>
<videomuted xmlns='http://jitsi.org/jitmeet/video'>false</videomuted><x xmlns="http://jabber.org/protocol/muc#user"><item affiliation="none" jid="af403c74-624f-46fa-9f0d-e590f267afb0@hangout.mydomain.org/fed0c279-4b75-404c-996d-8b9fedf7461d" role="participant"><reason></reason><actor jid=""/></item></x></presence>

I'm seeing this.

**Comment by aaronkvanmeerten** [comment]
How is your jibri configured?  You should have a jibri user on the prosody server, and that is the account that the jibri should be using to connect the XMPP control piece.  Make sure that you have the correct domain in prosody, and that your jibri is using that domain to authenticate.  In our example documentation, we have an auth.YOURDOMAIN VirtualHost which we then use prosodyctl to register a user account against.  Then jibri is configured to connect as a user on this auth virtual host.  Usually jicofo is also configured the same way, so if you've done a stock install this should Just Work (TM).

**Comment by nightstryke** [comment]
Well i've reinstalled jitsi-meet using the nightly ubuntu install method, and reinstalled jibri and now I can input a stream key so I'm almost there, unfortunately the stream fails to start and it gives me the error failed to start live stream.

**Comment by aaronkvanmeerten** [comment]
Great!  So the next place to look will the jibri logs.  These show up usually in /var/log/local/jibri-xmpp.log, depending on how you have the service set up and what logger you use on your system, etc.  Jibri will attempt to start, check the audio levels, then check that it's connecting to the room, and then finally check that ffmpeg is streaming properly to youtube.  If any of these checks fail, you will receive a stream fails to start message in jitsi meet.  Also, the jicofo logs may help, as they will show whether the jibri is being contacted (and which one was chosen, in case you have a pool of jibris).

**Comment by nightstryke** [comment]
Not finding a jibri-xmpp.log anywhere, I did find a jibri-audio_check.log in /tmp and the only real error is this.
`Warning: rate is not accurate (requested = 44100Hz, got = 48000Hz)`

**Comment by aaronkvanmeerten** [comment]
jibri-xmpp.log may not be where your logs go.  Instead they may be in your standard syslog file.  The jibri logs will be where you want to look however.  It's likely that if the jibri pending timeout occurs, that the real errors will be in your jibri logs.

I don't really know if anybody can be paid for this, it's not something our team contracts for.  There may be other experts out there who might help, but I'm not aware of them, sorry to say.

**Comment by nightstryke** [comment]
@aaronkvanmeerten Could you ask your team about this, I'm losing my mind on this.

**Comment by nightstryke** [comment]
Apparently my problem is the boshdomain_prefix line in the config.json removing it got live stream working. Though he live stream works for a while about 3 to 5 minute and then i get a network connection error. Any ideas on that?
