### ISSUE TITLE
ffmpeg for live streaming on jibir

### ISSUE THREAD

**Issue by fcessi** [jitsi/jibri#475]
i just want to ask how can I get input from jibri for my rtmp server? 
i follow a lot of solutions in github but it's not working. 
example : https://blog.telzee.io/jibri-streaming-and-recording-to-custom-rmtp-endpoint/

I know a lot about the ffmpeg but I don't know what is the ffmpeg input ?
`ffmpeg -y -v info -f x11grab -draw_mouse 0 -r 30 -s 1280x720 -thread_queue_size 4096 -i :0.0+0,0 -f alsa -thread_queue_size 4096 -i snd_aloop -acodec aac -strict -2 -ar 44100 -c:v libx264 -preset veryfast -maxrate 2976k -bufsize 5952k -pix_fmt yuv420p -r 30 -crf 25 -g 60 -tune zerolatency -f flv rtmp://my_server:1935/live/test`

snd_loop is not an input for FFmpeg. input should be a file or URL . but I don't know which URL is good for FFmpeg input?

**Comment by bgrozev** [comment]
The inputs come from `alsa` and `x11grab`

**Comment by fcessi** [comment]
i run this command 
`ffmpeg -y -v info -f x11grab -draw_mouse 0 -r 30 -s 1280x720 -thread_queue_size 4096 -i :0.0+0,0 -f alsa -thread_queue_size 4096 -i x11grab -acodec aac -strict -2 -ar 44100 -c:v libx264 -preset veryfast -maxrate 2976k -bufsize 5952k -pix_fmt yuv420p -r 30 -crf 25 -g 60 -tune zerolatency -f flv rtmp://myserver:1935/live/test`

i got this error 
![image](https://user-images.githubusercontent.com/8588813/163852889-5807ebc8-455f-45c4-8cce-0495291e9476.png)


can you give me an example to send stream to my rtmp server by ffmpeg? i really confused
@bgrozev

**Comment by damencho** [comment]
use the rtmp url in jitsi-meet interface instead of providing the youtube key.

**Comment by fcessi** [comment]
@damencho it's not working in the jitsi-meet interface. 
i tried before but it's not valid for jitsi
I got "Stream is failing error" when I put my rtmp URL on jitsi interface

**Comment by damencho** [comment]
Does it reach jibri? Any logs in jibri?

**Comment by fcessi** [comment]
no, it does not reach jibri. it's just showed an error on UI jitsi interface

**Comment by fcessi** [comment]
@damencho i can't set rtmp in the interface. it's not valid. can you show me an example? 

it would be good if you provide a ffmpeg command to send live stream to rtmp server.

**Comment by fcessi** [comment]
@bgrozev can you open the issue? my problem is not solved yet :)

**Comment by bgrozev** [comment]
We use open github issues to track problems with the software that we need to address. Please use https://community.jitsi.org for questions

**Comment by damencho** [comment]
![Screenshot 2022-04-19 at 15 25 56](https://user-images.githubusercontent.com/3263098/164089991-d6c661a4-81fa-42d0-a854-ac936fd7cd85.png)

If I do this, and hit Start it reaches jibri and I got a reposponse:
![Screenshot 2022-04-19 at 15 26 56](https://user-images.githubusercontent.com/3263098/164090079-855cf10f-3e1f-4fc7-b9ab-43430bc5cf90.png)
