### ISSUE TITLE
Recipient not in room

### ISSUE THREAD

**Issue by animer3009** [jitsi/jibri#48]
Hi. 
I installed jibri. when i start services some user connects in room. room name is added in config.json.
the moderators options goes to this jibri user.
when i trying start streaming, in jitsi server i getting error like: ignored from non moderator user.

when i doing so that this jibri user is not moderator and trying start streaming, in jitsi server getting message like: Recipient not in room. And starting streaming is failing.

How to do so as in meet.jit.si (there is no connected some user)?
And what i must correct to start streaming?

p.s. when i trying self test as documented, all works fine. i getting connecting image in youtube stream page.

**Comment by aaronkvanmeerten** [comment]
Jibri uses a MUC in two ways.  The first way is meant to be to allow jicofo a means to discover them.  This MUC is never meant to host a real meeting, and often happens on a different MUC component than the rest of the meet runs.

If you are having your jibri explicitly join a room that your users are in, using config.json, you will experience exactly the effect you described.  Instead, set jibri to join a muc room that users will never join, or even better, set it to join a muc room on a separate muc component (so instead of conference.YOURDOMAIN, use internal.YOURDOMAIN or something of that nature).  This must already be set up in prosody to work, and you must have the corresponding setting for the jibro brewery room properly set in jicofo as well.

Once this is working, then when jibri gets called by jicofo to begin recording (when the "Start Live Stream" button is pressed), the jibri will connected via chrome to the room it was invited to.  The jibri should then present a separate set of credentials which authenticates it as a user which should be hidden.  Finally, the hiddenDomain setting in jitsi meet config.js must be set to this domain.  Once all these things are in place, you will see the same behavior as on meet.jit.si.

**Comment by animer3009** [comment]
not working...
i have set of domains goes to jitsi server.
jitsi.oracle.ge
conference.jitsi.oracle.ge
auth.jitsi.oracle.ge
jitsi-videobridge.jitsi.oracle.ge
focus.jitri.oracle.ge
this all to 85.117.36.227

Also i have domain:
recorder.jitsi.oracle.ge
it to jibri 85.117.36.229 
(for experimental i transfer it to 85.117.36.227 but result was same.)

Here is my log. I trying configure it 1 week but...

Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,260 INFO     on_jibri_iq: <iq to="jibri@auth.jitsi.oracle.ge/afb04fb6-939e-4b81-9680-6a7581726803" from="jibri@conference.jitsi.oracle.ge/focus" id="amlicmlAYXV0aC5qaXRzaS5vcmFjbGUuZ2UvYWZiMDRmYjYtOTM5ZS00YjgxLTk2ODAtNmE3NTgxNzI2ODAzAEhLb243LTgxACUvrsnrRIAHN70KhQgo/bo=" type="set"><jibri xmlns="http://jitsi.org/protocol/jibri" recording_mode="stream" room="test@conference.jitsi.oracle.ge" streamid="gzgc-5fgb-979u-136d" action="start" /></iq>
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,261 INFO     sending presence: <presence to="jibri@conference.jitsi.oracle.ge" xml:lang="en"><jibri-status xmlns="http://jitsi.org/protocol/jibri" status="busy" /></presence>
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,262 INFO     Client options for host: {'brewery_prefix': 'conference.', 'roompass': '', 'selenium_xmpp_login': 'recorder@recorder.jitsi.oracle.ge', 'roomname': 'jibri', 'url': 'https://jitsi.oracle.ge/%SUBDOMAIN%%ROOM%', 'boshdomain_prefix': 'recorder.', 'jid': 'jibri@auth.jitsi.oracle.ge', 'selenium_xmpp_password': 'recorderpass', 'mucserver_prefix': 'conference.', 'jid_username': 'jibri', 'boshdomain': 'recorder.jitsi.oracle.ge', 'selenium_xmpp_username': 'recorder', 'selenium_xmpp_prefix': 'recorder.', 'usage_timeout': 0, 'xmpp_domain': 'jitsi.oracle.ge', 'nick': 'jibri-9757306421406237', 'password': 'jibripass', 'recording_directory': './recordings', 'room': 'jibri@conference.jitsi.oracle.ge', 'jidserver_prefix': 'auth.'}
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,262 INFO     Setting xmpp login from client options: recorder@recorder.jitsi.oracle.ge
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,262 INFO     Setting xmpp password from client options
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,262 INFO     Setting boshdomain from client options recorder.jitsi.oracle.ge
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,262 INFO     Setting xmpp_domain from client options jitsi.oracle.ge
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,263 INFO     Setting mucserver_prefix from client options conference.
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,263 INFO     Setting recording_directory from client options ./recordings
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,264 INFO     Start recording callback
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,264 INFO     update_jibri_status
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,264 INFO     looping through queue for host 85.117.36.227
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,264 INFO     Starting jibri
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,264 INFO     Starting selenium attempt 1/3 pjsua_flag:False
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,265 INFO     overriding config.hosts.domain with boshdomain: recorder.jitsi.oracle.ge
Oct 16 06:02:37 recorder app.py[1468]: 2017-10-16 06:02:37,265 INFO     starting jibri selenium, url=https://jitsi.oracle.ge/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.jitsi.oracle.ge", google_account=None, xmpp_login=recorder@recorder.jitsi.oracle.ge
Oct 16 06:02:49 recorder app.py[1468]: 2017-10-16 06:02:49,452 INFO     Audio levels confirmed OK.
Oct 16 06:02:49 recorder app.py[1468]: 2017-10-16 06:02:49,452 INFO     Launching URL: https://jitsi.oracle.ge/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.jitsi.oracle.ge"
Oct 16 06:02:49 recorder app.py[1468]: 2017-10-16 06:02:49,452 INFO     setting jibri identifiers: display Live Stream -  email recorder@jitsi.org
Oct 16 06:02:51 recorder app.py[1468]: 2017-10-16 06:02:51,950 INFO     setting jibri identifiers: xmpp_username_override recorder@recorder.jitsi.oracle.ge
Oct 16 06:02:53 recorder app.py[1468]: 2017-10-16 06:02:53,809 INFO     starting to wait for XMPPConnected
Oct 16 06:02:53 recorder app.py[1468]: 2017-10-16 06:02:53,862 INFO     waiting +5 = 0 < 60 for XMPPConnected
Oct 16 06:02:58 recorder app.py[1468]: 2017-10-16 06:02:58,877 INFO     XMPP connected, done waiting
Oct 16 06:02:58 recorder app.py[1468]: 2017-10-16 06:02:58,877 INFO     starting to wait for DownloadBitrate
Oct 16 06:02:58 recorder app.py[1468]: 2017-10-16 06:02:58,886 INFO     waiting +5 = 0 < 60 for DownloadBitrate
Oct 16 06:03:03 recorder app.py[1468]: 2017-10-16 06:03:03,894 INFO     waiting +5 = 5 < 60 for DownloadBitrate
Oct 16 06:03:08 recorder app.py[1468]: 2017-10-16 06:03:08,904 INFO     waiting +5 = 10 < 60 for DownloadBitrate
Oct 16 06:03:13 recorder app.py[1468]: 2017-10-16 06:03:13,914 INFO     waiting +5 = 15 < 60 for DownloadBitrate
Oct 16 06:03:18 recorder app.py[1468]: 2017-10-16 06:03:18,925 INFO     waiting +5 = 20 < 60 for DownloadBitrate
Oct 16 06:03:23 recorder app.py[1468]: 2017-10-16 06:03:23,933 INFO     waiting +5 = 25 < 60 for DownloadBitrate
Oct 16 06:03:28 recorder app.py[1468]: 2017-10-16 06:03:28,943 INFO     waiting +5 = 30 < 60 for DownloadBitrate
Oct 16 06:03:33 recorder app.py[1468]: 2017-10-16 06:03:33,956 INFO     waiting +5 = 35 < 60 for DownloadBitrate
Oct 16 06:03:38 recorder app.py[1468]: 2017-10-16 06:03:38,967 INFO     waiting +5 = 40 < 60 for DownloadBitrate
Oct 16 06:03:43 recorder app.py[1468]: 2017-10-16 06:03:43,977 INFO     waiting +5 = 45 < 60 for DownloadBitrate
Oct 16 06:03:48 recorder app.py[1468]: 2017-10-16 06:03:48,986 INFO     waiting +5 = 50 < 60 for DownloadBitrate
Oct 16 06:03:53 recorder app.py[1468]: 2017-10-16 06:03:53,997 INFO     waiting +5 = 55 < 60 for DownloadBitrate
Oct 16 06:03:59 recorder app.py[1468]: 2017-10-16 06:03:59,005 INFO     Timed out waiting for download bitrate
Oct 16 06:03:59 recorder app.py[1468]: 2017-10-16 06:03:59,005 ERROR    Jibri Startup exception during attempt 1/3: unorderable types: NoneType() > int()
Oct 16 06:03:59 recorder app.py[1468]: 2017-10-16 06:03:59,005 INFO     start_jibri_selenium returned retcode=9999 during attempt 1/3
Oct 16 06:03:59 recorder app.py[1468]: 2017-10-16 06:03:59,005 INFO     Starting selenium attempt 2/3 pjsua_flag:False
Oct 16 06:03:59 recorder app.py[1468]: 2017-10-16 06:03:59,006 INFO     overriding config.hosts.domain with boshdomain: recorder.jitsi.oracle.ge
Oct 16 06:03:59 recorder app.py[1468]: 2017-10-16 06:03:59,006 INFO     starting jibri selenium, url=https://jitsi.oracle.ge/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.jitsi.oracle.ge", google_account=None, xmpp_login=recorder@recorder.jitsi.oracle.ge
Oct 16 06:04:04 recorder app.py[1468]: 2017-10-16 06:04:04,492 INFO     Audio levels confirmed OK.
Oct 16 06:04:04 recorder app.py[1468]: 2017-10-16 06:04:04,492 INFO     Launching URL: https://jitsi.oracle.ge/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.jitsi.oracle.ge"
Oct 16 06:04:04 recorder app.py[1468]: 2017-10-16 06:04:04,492 INFO     setting jibri identifiers: display Live Stream -  email recorder@jitsi.org
Oct 16 06:04:06 recorder app.py[1468]: 2017-10-16 06:04:06,782 INFO     setting jibri identifiers: xmpp_username_override recorder@recorder.jitsi.oracle.ge
Oct 16 06:04:08 recorder app.py[1468]: 2017-10-16 06:04:08,676 INFO     starting to wait for XMPPConnected
Oct 16 06:04:08 recorder app.py[1468]: 2017-10-16 06:04:08,686 INFO     waiting +5 = 0 < 60 for XMPPConnected
Oct 16 06:04:13 recorder app.py[1468]: 2017-10-16 06:04:13,698 INFO     XMPP connected, done waiting
Oct 16 06:04:13 recorder app.py[1468]: 2017-10-16 06:04:13,698 INFO     starting to wait for DownloadBitrate
Oct 16 06:04:13 recorder app.py[1468]: 2017-10-16 06:04:13,704 INFO     waiting +5 = 0 < 60 for DownloadBitrate
Oct 16 06:04:18 recorder app.py[1468]: 2017-10-16 06:04:18,712 INFO     waiting +5 = 5 < 60 for DownloadBitrate
Oct 16 06:04:23 recorder app.py[1468]: 2017-10-16 06:04:23,719 INFO     waiting +5 = 10 < 60 for DownloadBitrate
Oct 16 06:04:28 recorder app.py[1468]: 2017-10-16 06:04:28,730 INFO     waiting +5 = 15 < 60 for DownloadBitrate
Oct 16 06:04:33 recorder app.py[1468]: 2017-10-16 06:04:33,738 INFO     waiting +5 = 20 < 60 for DownloadBitrate
Oct 16 06:04:38 recorder app.py[1468]: 2017-10-16 06:04:38,748 INFO     waiting +5 = 25 < 60 for DownloadBitrate
Oct 16 06:04:43 recorder app.py[1468]: 2017-10-16 06:04:43,759 INFO     waiting +5 = 30 < 60 for DownloadBitrate
Oct 16 06:04:48 recorder app.py[1468]: 2017-10-16 06:04:48,770 INFO     waiting +5 = 35 < 60 for DownloadBitrate
Oct 16 06:04:53 recorder app.py[1468]: 2017-10-16 06:04:53,780 INFO     waiting +5 = 40 < 60 for DownloadBitrate
Oct 16 06:04:58 recorder app.py[1468]: 2017-10-16 06:04:58,790 INFO     waiting +5 = 45 < 60 for DownloadBitrate
Oct 16 06:05:03 recorder app.py[1468]: 2017-10-16 06:05:03,797 INFO     waiting +5 = 50 < 60 for DownloadBitrate
Oct 16 06:05:08 recorder app.py[1468]: 2017-10-16 06:05:08,803 INFO     waiting +5 = 55 < 60 for DownloadBitrate
Oct 16 06:05:13 recorder app.py[1468]: 2017-10-16 06:05:13,814 INFO     Timed out waiting for download bitrate
Oct 16 06:05:13 recorder app.py[1468]: 2017-10-16 06:05:13,815 ERROR    Jibri Startup exception during attempt 2/3: unorderable types: NoneType() > int()
Oct 16 06:05:13 recorder app.py[1468]: 2017-10-16 06:05:13,815 INFO     start_jibri_selenium returned retcode=9999 during attempt 2/3
Oct 16 06:05:13 recorder app.py[1468]: 2017-10-16 06:05:13,815 INFO     Starting selenium attempt 3/3 pjsua_flag:False
Oct 16 06:05:13 recorder app.py[1468]: 2017-10-16 06:05:13,815 INFO     overriding config.hosts.domain with boshdomain: recorder.jitsi.oracle.ge
Oct 16 06:05:13 recorder app.py[1468]: 2017-10-16 06:05:13,816 INFO     starting jibri selenium, url=https://jitsi.oracle.ge/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.jitsi.oracle.ge", google_account=None, xmpp_login=recorder@recorder.jitsi.oracle.ge
Oct 16 06:05:19 recorder app.py[1468]: 2017-10-16 06:05:19,263 INFO     Audio levels confirmed OK.
Oct 16 06:05:19 recorder app.py[1468]: 2017-10-16 06:05:19,263 INFO     Launching URL: https://jitsi.oracle.ge/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.jitsi.oracle.ge"
Oct 16 06:05:19 recorder app.py[1468]: 2017-10-16 06:05:19,264 INFO     setting jibri identifiers: display Live Stream -  email recorder@jitsi.org
Oct 16 06:05:22 recorder app.py[1468]: 2017-10-16 06:05:22,012 INFO     setting jibri identifiers: xmpp_username_override recorder@recorder.jitsi.oracle.ge
Oct 16 06:05:23 recorder app.py[1468]: 2017-10-16 06:05:23,955 INFO     starting to wait for XMPPConnected
Oct 16 06:05:23 recorder app.py[1468]: 2017-10-16 06:05:23,969 INFO     waiting +5 = 0 < 60 for XMPPConnected
Oct 16 06:05:28 recorder app.py[1468]: 2017-10-16 06:05:28,984 INFO     XMPP connected, done waiting
Oct 16 06:05:28 recorder app.py[1468]: 2017-10-16 06:05:28,984 INFO     starting to wait for DownloadBitrate
Oct 16 06:05:28 recorder app.py[1468]: 2017-10-16 06:05:28,991 INFO     waiting +5 = 0 < 60 for DownloadBitrate
Oct 16 06:05:34 recorder app.py[1468]: 2017-10-16 06:05:34,001 INFO     waiting +5 = 5 < 60 for DownloadBitrate
Oct 16 06:05:39 recorder app.py[1468]: 2017-10-16 06:05:39,011 INFO     waiting +5 = 10 < 60 for DownloadBitrate
Oct 16 06:05:44 recorder app.py[1468]: 2017-10-16 06:05:44,021 INFO     waiting +5 = 15 < 60 for DownloadBitrate
Oct 16 06:05:49 recorder app.py[1468]: 2017-10-16 06:05:49,031 INFO     waiting +5 = 20 < 60 for DownloadBitrate
Oct 16 06:05:54 recorder app.py[1468]: 2017-10-16 06:05:54,039 INFO     waiting +5 = 25 < 60 for DownloadBitrate
Oct 16 06:05:59 recorder app.py[1468]: 2017-10-16 06:05:59,050 INFO     waiting +5 = 30 < 60 for DownloadBitrate
Oct 16 06:06:04 recorder app.py[1468]: 2017-10-16 06:06:04,060 INFO     waiting +5 = 35 < 60 for DownloadBitrate
Oct 16 06:06:09 recorder app.py[1468]: 2017-10-16 06:06:09,066 INFO     waiting +5 = 40 < 60 for DownloadBitrate
Oct 16 06:06:14 recorder app.py[1468]: 2017-10-16 06:06:14,076 INFO     waiting +5 = 45 < 60 for DownloadBitrate
Oct 16 06:06:19 recorder app.py[1468]: 2017-10-16 06:06:19,086 INFO     waiting +5 = 50 < 60 for DownloadBitrate
Oct 16 06:06:24 recorder app.py[1468]: 2017-10-16 06:06:24,096 INFO     waiting +5 = 55 < 60 for DownloadBitrate
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,106 INFO     Timed out waiting for download bitrate
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,107 ERROR    Jibri Startup exception during attempt 3/3: unorderable types: NoneType() > int()
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,107 INFO     start_jibri_selenium returned retcode=9999 during attempt 3/3
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,107 INFO     start_jibri_selenium returned retcode=9999
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,107 INFO     jibri_stop_callback run with status startup_selenium_error
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,107 INFO     queueing error error|startup_selenium_error for host 85.117.36.227
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,107 INFO     queueing job for jibri_watcher
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,107 INFO     jibri_watcher received job, now watching ffmpeg and selenium with a timeout of 0.
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,107 INFO     jibri_watcher finished loop...
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,107 INFO     jibri_watcher starting up...
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,550 INFO     got msg from main: error|startup_selenium_error
Oct 16 06:06:29 recorder app.py[1468]: 2017-10-16 06:06:29,551 INFO     sending status update: <iq to="jibri@conference.jitsi.oracle.ge/focus" id="b5921465-cbb0-45e2-a1e8-09246c550b38-7" type="set"><jibri xmlns="http://jitsi.org/protocol/jibri" status="failed"><error xmlns="jabber:client" type="wait" code="504"><remote-server-timeout xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Startup error: Selenium error</text><retry xmlns="http://jitsi.org/protocol/jibri" /></error></jibri></iq>
Oct 16 06:06:32 recorder app.py[1468]: 2017-10-16 06:06:32,215 ERROR    Exception in callback jibri_start_callback(<jibrixmppcli...x7fb014209390>, '', 'stream', 'gzgc-5fgb-979u-136d', '', '', ...) at /home/jibri/jibri-xmpp-client/app.py:310
Oct 16 06:06:32 recorder app.py[1468]: handle: <Handle jibri_start_callback(<jibrixmppcli...x7fb014209390>, '', 'stream', 'gzgc-5fgb-979u-136d', '', '', ...) at /home/jibri/jibri-xmpp-client/app.py:310>
Oct 16 06:06:32 recorder app.py[1468]: Traceback (most recent call last):
Oct 16 06:06:32 recorder app.py[1468]:   File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
Oct 16 06:06:32 recorder app.py[1468]:     self._callback(*self._args)
Oct 16 06:06:32 recorder app.py[1468]:   File "/home/jibri/jibri-xmpp-client/app.py", line 521, in jibri_start_callback
Oct 16 06:06:32 recorder app.py[1468]:     jibri_stop_callback('startup_selenium_error')
Oct 16 06:06:32 recorder app.py[1468]:   File "/home/jibri/jibri-xmpp-client/app.py", line 794, in jibri_stop_callback
Oct 16 06:06:32 recorder app.py[1468]:     finalize_recording()
Oct 16 06:06:32 recorder app.py[1468]:   File "/home/jibri/jibri-xmpp-client/app.py", line 203, in finalize_recording
Oct 16 06:06:32 recorder app.py[1468]:     call([finalize_recording_script,recording_directory])
Oct 16 06:06:32 recorder app.py[1468]:   File "/usr/lib/python3.5/subprocess.py", line 557, in call
Oct 16 06:06:32 recorder app.py[1468]:     with Popen(*popenargs, **kwargs) as p:
Oct 16 06:06:32 recorder app.py[1468]:   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
Oct 16 06:06:32 recorder app.py[1468]:     restore_signals, start_new_session)
Oct 16 06:06:32 recorder app.py[1468]:   File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
Oct 16 06:06:32 recorder app.py[1468]:     raise child_exception_type(errno_num, err_msg)
Oct 16 06:06:32 recorder app.py[1468]: PermissionError: [Errno 13] Permission denied
Oct 16 06:06:59 recorder app.py[1468]: 2017-10-16 06:06:59,558 WARNING  Timed out waiting for IqWait_b5921465-cbb0-45e2-a1e8-09246c550b38-7
Oct 16 06:06:59 recorder app.py[1468]: 2017-10-16 06:06:59,559 ERROR    Failed to send status update: <iq to="jibri@conference.jitsi.oracle.ge/focus" id="b5921465-cbb0-45e2-a1e8-09246c550b38-7" type="set"><jibri xmlns="http://jitsi.org/protocol/jibri" status="failed"><error xmlns="jabber:client" type="wait" code="504"><remote-server-timeout xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Startup error: Selenium error</text><retry xmlns="http://jitsi.org/protocol/jibri" /></error></jibri></iq>

**Comment by aaronkvanmeerten** [comment]
It appears that the chrome cannot connect properly.  I suggest testing the jibriselenium.py manually, using the username and password for the recorder domain.  This means a small change in the jibriselenium.py code in order to test by hand.  Be sure that the URL you use with -u is a valid meet URL, and that you have that conference open in another window so that the jibri gets video.

It is likely you have the wrong username/password or your jitsi meet is not properly configured.  Be sure you're running a new jitsi meet build, to ensure that everything else is properly set up.

**Comment by animer3009** [comment]
it was bosh domain prefix problem... jitsi quick install has not it. thanks.

but now i have other problem. after stop streaming i can not start new one without jibri-xmpp restart... i getting message in jitsi that service is  busy. there is no errors in jibri side....

**Comment by animer3009** [comment]
also i interested (want little describe) how to make record only function without youtube stream...
