### ISSUE TITLE
Deploy multiple jibri instances in a single kubernetes pod

### ISSUE THREAD

**Issue by VipinRaiP** [jitsi/jibri#484]
Jibri supports only one recording at a time.

We are using a kubernetes based setup. Jibri will be deployed in the kuberneted cluster.
We have configured multiple alsa loopback devices in the cluster node.

Requirement is to support multiple simultaneous recording from a single jibri pod.
How to run multiple jibri services in a single pod?

**Comment by saghul** [comment]
Please ask such questions in our community forum, we use GH for actual issues and feature requests.
