### ISSUE TITLE
JIBRI When recording a video, if the meeting name contains Chinese or Japanese, it will display an exception. Have you encountered it?

### ISSUE THREAD

**Issue by Lsq6647** [jitsi/jibri#485]

**Comment by saghul** [comment]
What exception?

**Comment by Lsq6647** [comment]
> 
![image](https://user-images.githubusercontent.com/71421018/173740601-947ab44b-d9f9-4d50-93ac-4194e018178f.png)

Hello, this is a screenshot of my recorded video. There should be a meeting name in Chinese and Japanese in the middle. Now it is like this.

**Comment by Lsq6647** [comment]
> 什么例外？

Hello, this is a screenshot of my recorded video. There should be a meeting name in Chinese and Japanese in the middle. Now it is like this.
![image](https://user-images.githubusercontent.com/71421018/173740801-f513c6d0-14e8-4a78-8cbb-76e0f6cb1440.png)

**Comment by saghul** [comment]
Ah that. Is this on meet.jit.si or your own deployment? If it's the latter then install the "noto" fonts.

**Comment by Lsq6647** [comment]
> Ah that. Is this on meet.jit.si or your own deployment? If it's the latter then install the "noto" fonts.

How can I install the noto font? I checked the documentation, but I didn't see the relevant operation steps. Can you tell me in detail, thank you very much, and trouble you.

**Comment by Lsq6647** [comment]
> Ah that. Is this on meet.jit.si or your own deployment? If it's the latter then install the "noto" fonts.

Hi, the problem is solved, thank you very much
