### ISSUE TITLE
Make more ffmpeg arguments configurable

### ISSUE THREAD

**Issue by jsurkont** [jitsi/jibri#486]
Currently only three `ffmpeg` arguments are configurable: `resolution`, `audioSource`, `audioDevice`. Would you consider making more (all) arguments configurable? I think `videoEncodePreset`, `h264ConstantRateFactor`, and `framerate` are especially useful. I could submit a PR for that.

**Comment by saghul** [comment]
I don't see why not. Thoughts @raluca8x8 @oanaianc @bbaldino ?

**Comment by ribeaud** [comment]
When do you plan to do a new release? We would really appreciate if we could profit from this feature as soon (!) as possible. I mean, this issue has been closed for more than 1y now... 🙊

**Comment by saghul** [comment]
This has definitely been released already. What version are you using?

**Comment by ribeaud** [comment]
Thanks for your blasting fast answer @saghul. Then, we probably do not really understand your release model... 😆 
[Here](https://github.com/jitsi/jibri/tags), I see that the last release happened **2019**. We are using `stable-8922`.

**Comment by damencho** [comment]
This is when v8 tag was created. the latest stable jibri is jibri_8.0-145-g1a4bb8e-1_all.deb 02-May-2023 11:56.
Which is same tag but the commit is from end of April 
https://github.com/jitsi/jibri/commit/1a4bb8e0e83082440a57664382393f74c4e80014

Jibri and Jigasi has a different release cycle than jitsi-meet where stable-8922 is two weeks old.

**Comment by ribeaud** [comment]
OK, I think, I slowly understand: [this](https://github.com/jitsi/docker-jitsi-meet/blob/master/jibri.yml) will pick `unstable` image by default, which contains all the latest changes.

And if I want to use the changes made here, I need a file named `jibri.conf` in `${CONFIG}/jibri:/config:Z`, correct?

**Comment by saghul** [comment]
Our Docker stable releases are made from the stable repo.

What setting do you need to customize? This is how the jibri config is generated for the Docker setup: https://github.com/jitsi/docker-jitsi-meet/blob/master/jibri/rootfs/defaults/jibri.conf

If you need to make an extra option configurable you can make the changes there and send a PR so we have a new env variable you can use.

**Comment by ribeaud** [comment]
Mmmh... Does it mean I can't somehow benefit from the changes implemented in **this** issue? I can only customise **jibri** via environment variables? If for instance, if I want to use a different `jibri.ffmpeg.h264-constant-rate-factor` (_ h264ConstantRateFactor_), what should I do?

**Comment by saghul** [comment]
> Mmmh... Does it mean I can't somehow benefit from the changes implemented in **this** issue? I can only customise **jibri** via environment variables?
> 
> If for instance, if I want to use a different `jibri.ffmpeg.h264-constant-rate-factor` (_ h264ConstantRateFactor_), what should I do?

Not in Docker, until we add an extra env variable for the setting you want.



> Mmmh... Does it mean I can't somehow benefit from the changes implemented in **this** issue? I can only customise **jibri** via environment variables?
> 
> If for instance, if I want to use a different `jibri.ffmpeg.h264-constant-rate-factor` (_ h264ConstantRateFactor_), what should I do?

Create a PR in the Docker repo where you add a new env variable for that setting. See the link I pasted before and you can see hopw we do it for other variables.

**Comment by ribeaud** [comment]
Hi @saghul. Done!

See https://github.com/jitsi/docker-jitsi-meet/pull/1603

**Comment by saghul** [comment]
Thank you!
