### ISSUE TITLE
Jibri cannot join meeting due to conflict between prejoin page config.

### ISSUE THREAD

**Issue by debendraoli** [jitsi/jibri#490]
## Description

Jitsi meet recently  deprecated `prejoinPageEnabled` config and Jibri is still using this old config override parameter when joining the call, if installation is using new config `prejoinConfig` which basically overrides the parameter coming from jibri hence jibri gets stuck on pre-join page forever.

## Current behavior

Jibri failing to join call due to conflict between deprecated and new config.

## Expected Behavior

Jibri should join the meeting without issue. 

## Possible Solution

Jibri should also use new config on new release or deprecated config should be respected until it is removed.

## Steps to reproduce

1. Configure Jitsi with Jibri on docker-compose.
2. Enable prejoin page.
3. Try recording. 

# Environment details
Latest `unstable`/`stable` containers for `prosody,jicofo,web` and `jvb,jibri` on Ubuntu 22.04 EC2

**Comment by saghul** [comment]
Are you sure you are testing the correct images? This was fixed already: https://github.com/jitsi/jibri/blob/260cee3a118462aa419ff3b2e0ca2ac4645b7a92/src/main/kotlin/org/jitsi/jibri/selenium/JibriSelenium.kt#L154-L155

**Comment by debendraoli** [comment]
I am using debian build, its plain jibri on ec2.

If I am not mistaken, it looks like it is not released.

**Comment by saghul** [comment]
@damencho When did we release a stable  jibri last?

**Comment by saghul** [comment]
It should be included them I reckon.

**Comment by debendraoli** [comment]
Thanks a lot for the info.

It appears cloudfront is not forwarding config values starting with `#`.
