### ISSUE TITLE
Jicofo cannot parse jicofo.conf following Jibri install

### ISSUE THREAD

**Issue by cahlenlee** [jitsi/jibri#499]
## Description
---
I get a disconnected session and the jicofo.log error below when trying to start a new meeting after installing Jibri using the official guide:

---
An uncaught exception occurred in thread=Thread[main,5,main]                                                   java.lang.ExceptionInInitializerError                              at org.jitsi.jicofo.Main.main(Main.java:53)        Caused by: com.typesafe.config.ConfigException$Parse: /etc/jitsi/jicofo/jicofo.conf: 26: Expecting close brace } or a comma, got '@' (Reserved character '@' is not allowed outside quotes) (if you intended '@' (Reserved character '@' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
---

It's referring to the second line in a section I added to jicofo.conf which the official guide asked for:

---
jibri: {
brewery-jid = “JibriBrewery@internal.auth.DOMAIN"
pending-timeout = 90 seconds
}
---

Removing that code caused Jitsi to work again, but then I can't record. What going on here?

## Current behavior
---
Jitsi Meeting can't start

## Expected Behavior
---
Jitsu Meeting starts and recording is possible

## Steps to reproduce
---
1. Install Jitsi Meet using official guide
2. Install Jibri using official guide

# Environment details
---
Ubuntu 20 Dedicated Server

**Comment by bbaldino** [comment]
It looks like your quote characters may be incorrect (sometimes some apps format them as "smart quotes", which not everything understands.  I can kinda see from your pasted config that the quote characters appear different.

**Comment by bgrozev** [comment]
Please use community.jitsi.org to discuss problems like this before opening an issue on gihtub.
