### ISSUE TITLE
video resolution problem

### ISSUE THREAD

**Issue by animer3009** [jitsi/jibri#50]
when i am recording video in 1280X720 there in left side is big black vertical line and jitsi participants list is not shown.
As i think, in this moment resolution is incorrect.
When i restarting xmpp and xorg service, all becomes ok...

how to correct?

**Comment by animer3009** [comment]
In jibri-xmpp-client/jibriselenium.py added:     
      self.options.add_argument('--window-size=1280,720')
      self.options.add_argument('--start-fullscreen')
instead of 
self.options.add_argument('--start-maximized')
and working fine for me

**Comment by aaronkvanmeerten** [comment]
are you using a window manager, or just running selenium/chrome directly against your X server?  We had similar problems before adding a window manager to the mix.  Yours may be a better solution going forward, so I'll look at making the window size a set of parameters (already on my TODO list anyway), and then using the argument as you've provided it.  Thanks for the feedback!

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian respository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
