### ISSUE TITLE
Jibri Multiple Record Settings

### ISSUE THREAD

**Issue by alkanpolat** [jitsi/jibri#519]
Hello, I have been working on installing Jitsi and Jibri for a few days. It is really difficult to find an up-to-date and stable installation guide. As far as I saw from an installation video of an Indian friend, this situation can be corrected by multiplexing the Jibri container. For now I will explain how to do this manually. I am planning to publish a video featuring jitsi docker deployment in the coming days.

`sudo docker ps`
After run the Jitsi and Jibri containers, you should see an output like this.
![image](https://github.com/jitsi/jibri/assets/19879269/2f355005-457e-4504-ab9e-f4013c0f2cd3)

You can then multiplex the jibri container by running these commands respectively.
_**Note: If your docker container names differ, edit the commands below according to your own container names.**_
```
sudo docker exec -it docker-jitsi-meet_jibri_1 bash
apt-get update
apt install nano
nano home/jibri/.asoundrc
``` 

Go to the file and edit its content like this

```
...
slave.pcm "hw:Loopback,1,1"
...
slave.pcm "hw:Loopback,1,0"
...
slave.pcm "hw:Loopback_1,0,0"
...
slave.pcm "hw:Loopback_1,0,1"
...
slave.pcm "hw:Loopback_1,1,1"
...
slave.pcm "hw:Loopback_1,1,0"
...
slave.pcm "hw:Loopback_2,0,0"
...
slave.pcm "hw:Loopback_2,0,1"
...
slave.pcm "hw:Loopback_2,1,1"
...
slave.pcm "hw:Loopback_2,1,0"
...
slave.pcm "hw:Loopback_3,0,0"
...
slave.pcm "hw:Loopback_3,0,1"
...
slave.pcm "hw:Loopback_3,1,1"
...
slave.pcm "hw:Loopback_3,1,0"
...
slave.pcm "hw:Loopback_4,0,0"
...
slave.pcm "hw:Loopback_4,0,1"
...
slave.pcm "hw:Loopback_4,1,1"
...
slave.pcm "hw:Loopback_4,1,0"
...

```
```
exit
sudo docker exec -t docker-jitsi-meet_jibri_1 sed -i 's/Loopback/0/g' /home/jibri/.asoundrc
sudo docker restart docker-jitsi-meet_jibri_1
```

```
sudo docker-compose -f docker-compose.yml up -d --scale jibri=2
sudo docker exec -t docker-jitsi-meet_jibri_2 sed -i 's/Loopback/0/g' /home/jibri/.asoundrc
sudo docker restart docker-jitsi-meet_jibri_2
```

You can create as many jibri containers as you want using this method. Like this
```
sudo docker-compose -f docker-compose.yml up -d --scale jibri=3
sudo docker exec -t docker-jitsi-meet_jibri_3 sed -i 's/Loopback/0/g' /home/jibri/.asoundrc
sudo docker restart docker-jitsi-meet_jibri_3
```

`sudo docker ps `

In the last case, when you check, you should get an output like the following.
**_Note: The jitsi/whiteboard container should not appear on your screen._**
![image](https://github.com/jitsi/jibri/assets/19879269/77e842d0-145a-4c7b-9204-ea5d991cb1c0)

Indian friend's video with Jibri multiple record explanation and many more customizations
https://www.youtube.com/watch?v=5zANUyjAXPg&ab_channel=HC

and document file
https://drive.google.com/file/d/1SWi9m7XOivJjitj8ufgBDZB8XZHvLcpY/view

**Comment by saghul** [comment]
Those instructions are outdated, the Jibri container no longer needs an audio device.

You can just use different names and you're good to go.

**Comment by alkanpolat** [comment]
> Those instructions are outdated, the Jibri container no longer needs an audio device.
> 
> You can just use different names and you're good to go.

thx

**Comment by saghul** [comment]
Depends on how you orchestrate your containers. With  Compose you can just copy the Jibri file and that's it.

**Comment by talalgujjar100** [comment]
Hi Is there any clear documentation or guide if i want to record multiple meetings at the same time
using jibri hosted on digital ocean without dockers

**Comment by saghul** [comment]
There isn't. You need 1 Jibri instance to record 1 meeting, so Docker is the simplest way.

You no longer need to do anything with ALSA devices on the host, as PulseAudio takes care of it.
