### ISSUE TITLE
How to jitsi meet recoarding upload on azure blob storage

### ISSUE THREAD

**Issue by brijesh231199** [jitsi/jibri#536]
Currently jitsi provide recoarding upload only on dropbox and local storage.

**Comment by saghul** [comment]
If you deploy your own Jibri you can ha it upload the recording anywhere with the finalization script.

We have no plans to add any more builtin options.

**Comment by RadhikBhojani** [comment]
Where we have to push this updated script file ?

**Comment by saghul** [comment]
In the finalize.sh script.
