### ISSUE TITLE
Jibri Recording Failed To Start on Windows Docker 

### ISSUE THREAD

**Issue by andrew-paes** [jitsi/jibri#548]
I know this is not the right place to ask for help, but I could't any properly related forum.

Well, I'm trying to have my Dicker Jitsi Meet running on my Windows with Jibri attached on that just to understand better the JaaS and see how can I use this on my side project.

So far I have done the following steps:

- Download the stable version of docker-jitsi-meet-stable-9753.zip;
- Created a new .env file as documentation;
- Set passwords on security section of .env file
- Added the following lines at end of .env file:
    - ENABLE_DROPBOX=0
    - ENABLE_RECORDING=1
    - ENABLE_TRANSCRIPTIONS=1
    - JIBRI_BREWERY_MUC=jibribrewery
    - JIBRI_RECORDING_DIR=/config/recordings
- on powershell `docker compose -f docker-compose.yml -f jibri.yml up -d`

Services started and are running, so I can create and join a room.

But, when I ask for recording the meet, it appears as an DropBox icon:
![image](https://github.com/user-attachments/assets/e1965f74-e85e-4d60-ba7f-3662d74981e7)

And a few seconds later it says the recording has failed:
![image](https://github.com/user-attachments/assets/e0088fc3-e579-43c6-a8f0-96a8dba3abd5)

I was trying to follow this documentation:
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/

And it's saying:
> If you want to use jibri too, first **configure a host as described in Jitsi Broadcasting Infrastructure configuration** section and then run Docker Compose as follows:

So I came hereon the repo where it says something about that:
https://github.com/jitsi/jibri?tab=readme-ov-file#config-files

The things is, how do I set my configuration properly to have it running on localhost on my Docker Compose?

Looking into Docker Jibri logs, the most important line I think is:
> 2024-10-21 14:25:24 Jibri 2024-10-21 17:25:24.222 SEVERE: [74] [session_id=1449d157-f976-493f-bbe7-11c9eefeb232] JibriSelenium.joinCall$lambda$3#333: An error occurred while joining the call
> 2024-10-21 14:25:24 org.openqa.selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED
> 2024-10-21 14:25:24   (Session info: chrome=126.0.6478.126)
> 2024-10-21 14:25:24   (Driver info: chromedriver=126.0.6478.182 (5b5d8292ddf182f8b2096fa665b473b6317906d5-refs/branch-heads/6478@{#1776}),platform=Linux 5.15.153.1-microsoft-standard-WSL2 x86_64) (WARNING: The server did not provide any stacktrace information)

The full log if you want to see is:
[jitsi-jibri-stable-9753.log](https://github.com/user-attachments/files/17464984/jitsi-jibri-stable-9753.log)

**Comment by damencho** [comment]
Have you set your correct link for the deployment in the https://github.com/jitsi/docker-jitsi-meet/blob/a5b719c453ff104542d14412fd79c0eb6bf81843/env.example#L32?


> I know this is not the right place to ask for help, but I could't any properly related forum.

The correct place for questions is already written in the template of any issue you try to create:
```
Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.
```

**Comment by damencho** [comment]
Moving discussion in the community forum: https://community.jitsi.org/t/jibri-recording-failed-to-start-on-windows-docker/134954
