### ISSUE TITLE
Pjsua crashing on trying to use cloop as capture device

### ISSUE THREAD

**Issue by yokovaski** [jitsi/jibri#60]
Hi,

A while ago I saw a demonstration of Jitsi using Jibri for connecting a videoroom to a Jitsi videoconference: https://www.youtube.com/watch?v=TGloLKOrvmo&t=1306s. I would love to reproduce this result, but I am having trouble getting pjsua to work correctly. 

I have set the pjsua flags in app.py and jibriselenium.py to true and the start-pjsua.sh script is called. I also changed `--alsa-input-device=plughw:1,1` to `--alsa-input-device=plug:asnoop` in jibriselenium.py on line 63. I compiled pjproject 2.7.1 with `./configure --disable-speex-aec --disable-speex-codec`. In start-pjsua.sh I changed `CAPTURE_DEV=23` and `PLAYBACK_DEV=24` to the ids of cloop and ploop. 

I am using a pjsua.config with the following params:
`--local-port 0
--id sip:100@example.com
--realm *
--username 100
--password secretpassword`

However pjsua crashes with a segfault (139) everytime I try to start it.  Yesterday I send an email to the jitsi-users mailing list (http://lists.jitsi.org/pipermail/users/2017-December/013803.html) but so far I have not been lucky enough to receive a reply. 

Could someone give me some insight in what I am missing here? A bit of documentation on how to use pjsua with Jibri would also be nice :)

**Comment by yokovaski** [comment]
Apparently using cloop as capture device for pjsua is not correct.

I have two loopback devices. amix and asnoop are on device 0, ploop and cloop are on device 1.
sndinfo presents a list of 21 devices in my case. 
Using `plughw:CARD=Loopback,DEV=1` as capture device is the solution. I don't know how or why, but maybe this will help someone in the future.

**Comment by fuqiangleon** [comment]
@yokovaski 
Hello sir, 

> Apparently using cloop as capture device for pjsua is not correct.
> 
> I have two loopback devices. amix and asnoop are on device 0, ploop and cloop are on device 1.
> sndinfo presents a list of 21 devices in my case.
> Using `plughw:CARD=Loopback,DEV=1` as capture device is the solution. I don't know how or why, but maybe this will help someone in the future.

As you said ,we should use plughw:CARD=Loopback,DEV=1 as capture device ,and what's the playback device id which we should use ?

Hope get your help. many thanks.

**Comment by yokovaski** [comment]
@fuqiangleon It has been quite a while since I worked on this. I do not mention the playback device in my solution. Therefore I think I used ploop as playback device. The id might differ from system to system.

But as I said, it has been quite a while. the only thing I documented myself was that I had issues using cloop as capture device and that the solution was to use `capture_device=21` which listed as plughw:CARD=Loopback,DEV=1. 

I recall that I compiled an older version of pjsua in order to use sndinfo to get that list of devices.

**Comment by fuqiangleon** [comment]
@yokovaski   Thanks for your reply 
Actually I read your answer in community https://community.jitsi.org/t/jitsi-users-issues-with-jibri-and-pjsua/13304
 I compiled the sndinfo command and executed your python script ,but it return an code 06 .i will upload all data below , could you check it for me please  when you have time  .
Thank you very much. your answer is very helpful for me 

Have a good day.
[audio.txt](https://github.com/jitsi/jibri/files/3259719/audio.txt)
[sndinfo.txt](https://github.com/jitsi/jibri/files/3259721/sndinfo.txt)

**Result of python script below:**
python 1.py -d Loopback
06root@iZm5edyykkqb7qrnpll7ajZ:~#
