### ISSUE TITLE
jibri - Recording and saving video file

### ISSUE THREAD

**Issue by sreenivaska** [jitsi/jibri#62]
Hi,
I have installed JIBRI with the instructions provided [here](https://github.com/jitsi/jibri). 
I tested jibri using start-ffmpeg.sh and it created new filename.flv file but it contains only "Connecting" message on the blank screen.

When I connected jibri to jitsi-meet conference and start the "jibri-xmpp" service, an user "Fellow Jitster" has been connected to the given Conference, recorded video does not show the actual video of the conference participants, but only the "Connecting" message.

Please let me know how to fix this issue and what additional configurations to be done .
Thanks in advance.

**Comment by sreenivaska** [comment]
@aaronkvanmeerten 
Can you please me in the Jibri recording feature.

**Comment by Ark74** [comment]
I believe this have been answered here https://github.com/jitsi/jibri/issues/47

>There is no plans to make auto-recording a feature at the moment.

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian repository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
