### ISSUE TITLE
Jibri startup exception

### ISSUE THREAD

**Issue by yokovaski** [jitsi/jibri#63]
Hi,

I installed Jibri on Ubuntu 16.04 by following the README. I am able to start a live stream in Jitsi Meet. However, Jibri crashes during starting Selenium with the message `start_jibri_selenium returned retcode=9999`. 

Starting jibriselenium.py manually doesn't show any errors. starting the launch_recording.sh script does also work. Starting both manually results in a successful live stream to YouTube.

The weird part is what is been shown on `DISPLAY=:0` when Jibri is started from Jitsi Meet. A white screen is shown briefly and after that a piano sound is being [played](https://youtu.be/OIKtQIk-xAg) (this has been recorded manually).

I am using `Google Chrome 64.0.3282.119` and `ChromeDriver 2.35.528139`.

_edit_
Discovered that the piano sound is playing because the audio needs to be checked. 
app.py times out on executing `js.driver.get(audio_url)` on line 793

When I skip the audio check entirely, everything seems to be working fine. Chrome has joined the video conference and ffmpeg is capturing and streaming `DISPLAY=:0`.

**Comment by yokovaski** [comment]
Somehow `js.driver.get(audio_url)` is not returning when the default_audio_url is used. Setting `audio_url="https://soundcloud.com/alanwalker/alan-walker-fade"` does not cause a time out on checking the audio. 

Maybe something is wrong with playing a wav in the browser?

**Comment by nightstryke** [comment]
@yokovaski Where are you adding the audio_url setting?

**Comment by yokovaski** [comment]
You can set the `default_audio_url` on line 34 of [app.py](https://github.com/jitsi/jibri/blob/master/jibri-xmpp-client/app.py#L34)

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian repository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
