### ISSUE TITLE
Stream to self-hosted server

### ISSUE THREAD

**Issue by tes5884** [jitsi/jibri#64]
Can I use jibri to stream my jitsi instance to my hosted rtmp server? Are there any docs for this?

**Comment by bgrozev** [comment]
See here
https://github.com/jitsi/jibri/blob/master/scripts/launch_recording.sh#L13

**Comment by tes5884** [comment]
thanks @bgrozev !

**Comment by yuvrajchowdary** [comment]
> See here
> https://github.com/jitsi/jibri/blob/master/scripts/launch_recording.sh#L13
Page not found.
Any other References?
