### ISSUE TITLE
Jibri Selenium user had permission issue 'Failed to access your camera'.

### ISSUE THREAD

**Issue by cheelibrahmaiah** [jitsi/jibri#69]
Hi All,

I had setup jibri recording feature successfully, we can able to record the JITSI conference in separate file by using start selenium user and  ffmpeg command. I have a problem Jibri Selenium user is connected to JITSI Conference and record the conference into a file, In that recorded file we had permission issue 'Failed to access your camera'.

Appreciate any open suggestions.

**Comment by krisalay** [comment]
@cheelibrahmaiah 
Hi,
Seems like you have successfully setup the recording feature using jibri. I have been trying to do the same for last one week but I am not able to do so.
When I manually run the command: `./start-ffmpeg.sh filename.mp4` then it creates a file with content "connecting".
Can you please let me know the proper steps for the jibri integration with jitsi-meet?

**Comment by cheelibrahmaiah** [comment]
@Kumar Kisalay
Please share your requirement explain in detail, and tell me the process
you followed to setup Jibri.
if possible share the logs as well, I will help you.

**Comment by krisalay** [comment]
@cheelibrahmaiah 
I am now getting the prompt for stream key but after providing it, in jicofo logs it gives jibri status=off

Jicofo Log:
`org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Publish new JIBRI status: <jibri-recording-status xmlns='http://jitsi.org/protocol/jibri' status='off'/> in: roomname@conference.domain.com`

Jibri-xmpp log:
`Mar 21 17:50:58 jibri jibri-xmpp[1949]: 2018-03-21 17:50:58,439 INFO     Creating a client for hostname: meet-07.talview.com with options: {'usage_timeout': 0, 'roomname': 'TheBrewery', 'roompass': 
Mar 21 17:50:58 jibri jibri-xmpp[1949]: 2018-03-21 17:50:58,460 WARNING  jid property deprecated. Use boundjid.bare
Mar 21 17:50:58 jibri jibri-xmpp[1949]: 2018-03-21 17:50:58,461 INFO      * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Mar 21 17:50:58 jibri jibri-xmpp[1949]: 2018-03-21 17:50:58,461 INFO     jibri_watcher starting up...
Mar 21 17:50:59 jibri jibri-xmpp[1949]: 2018-03-21 17:50:59,058 INFO     Negotiating TLS
Mar 21 17:50:59 jibri jibri-xmpp[1949]: 2018-03-21 17:50:59,059 INFO     Using SSL version: TLS 1.0
Mar 21 17:50:59 jibri jibri-xmpp[1949]: 2018-03-21 17:50:59,366 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED.
Mar 21 17:51:00 jibri jibri-xmpp[1949]: 2018-03-21 17:51:00,440 INFO     JID set to: jibri@auth.meet-07.talview.com/024122d7-799a-4eb4-95dd-bc2b3ea599c7
Mar 21 17:51:00 jibri jibri-xmpp[1949]: 2018-03-21 17:51:00,590 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED.
Mar 21 17:51:00 jibri jibri-xmpp[1949]: 2018-03-21 17:51:00,592 INFO     Starting up client <jibrixmppclient.JibriXMPPClient object at 0x7fb21327def0>, connecting to room TheBrewery@conference.meet-
Mar 21 17:51:00 jibri jibri-xmpp[1949]: 2018-03-21 17:51:00,743 INFO     sending presence: <presence to="TheBrewery@conference.meet-07.talview.com" xml:lang="en"><jibri-status xmlns="http://jitsi.or
Mar 21 17:51:00 jibri jibri-xmpp[1949]: 2018-03-21 17:51:00,745 INFO     Started up client <jibrixmppclient.JibriXMPPClient object at 0x7fb21327def0>
Mar 21 18:13:01 jibri jibri-xmpp[1949]: 2018-03-21 18:13:01,065 ERROR    Socket Error #110: Connection timed out
Mar 21 18:13:01 jibri jibri-xmpp[1949]: 2018-03-21 18:13:01,068 WARNING  Failed to send b'</stream:stream>'
Mar 21 18:13:01 jibri jibri-xmpp[1949]: 2018-03-21 18:13:01,071 INFO     Waiting for </stream:stream> from server
Mar 21 18:13:07 jibri jibri-xmpp[1949]: 2018-03-21 18:13:07,540 INFO     Negotiating TLS
Mar 21 18:13:07 jibri jibri-xmpp[1949]: 2018-03-21 18:13:07,542 INFO     Using SSL version: TLS 1.0
Mar 21 18:13:07 jibri jibri-xmpp[1949]: 2018-03-21 18:13:07,867 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED.
Mar 21 18:13:08 jibri jibri-xmpp[1949]: 2018-03-21 18:13:08,937 INFO     JID set to: jibri@auth.meet-07.talview.com/50008832-a4d2-450a-b84f-6922838b7fa8
Mar 21 18:13:09 jibri jibri-xmpp[1949]: 2018-03-21 18:13:09,089 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED.
Mar 21 18:13:09 jibri jibri-xmpp[1949]: 2018-03-21 18:13:09,091 INFO     Starting up client <jibrixmppclient.JibriXMPPClient object at 0x7fb21327def0>, connecting to room TheBrewery@conference.meet-
Mar 21 18:13:09 jibri jibri-xmpp[1949]: 2018-03-21 18:13:09,245 INFO     sending presence: <presence to="TheBrewery@conference.meet-07.talview.com" xml:lang="en"><jibri-status xmlns="http://jitsi.or
Mar 21 18:13:09 jibri jibri-xmpp[1949]: 2018-03-21 18:13:09,249 INFO     Started up client <jibrixmppclient.JibriXMPPClient object at 0x7fb21327def0>
Mar 21 18:35:11 jibri jibri-xmpp[1949]: 2018-03-21 18:35:11,754 ERROR    Socket Error #110: Connection timed out
Mar 21 18:35:11 jibri jibri-xmpp[1949]: 2018-03-21 18:35:11,757 WARNING  Failed to send b'</stream:stream>'
Mar 21 18:35:11 jibri jibri-xmpp[1949]: 2018-03-21 18:35:11,759 INFO     Waiting for </stream:stream> from server
Mar 21 18:35:18 jibri jibri-xmpp[1949]: 2018-03-21 18:35:18,438 INFO     Negotiating TLS
Mar 21 18:35:18 jibri jibri-xmpp[1949]: 2018-03-21 18:35:18,441 INFO     Using SSL version: TLS 1.0
Mar 21 18:35:18 jibri jibri-xmpp[1949]: 2018-03-21 18:35:18,767 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED.
Mar 21 18:35:19 jibri jibri-xmpp[1949]: 2018-03-21 18:35:19,852 INFO     JID set to: jibri@auth.meet-07.talview.com/04b5e1a9-3f22-4633-82da-b517487de0ad
Mar 21 18:35:20 jibri jibri-xmpp[1949]: 2018-03-21 18:35:20,009 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED.
Mar 21 18:35:20 jibri jibri-xmpp[1949]: 2018-03-21 18:35:20,009 INFO     Starting up client <jibrixmppclient.JibriXMPPClient object at 0x7fb21327def0>, connecting to room TheBrewery@conference.meet-
Mar 21 18:35:20 jibri jibri-xmpp[1949]: 2018-03-21 18:35:20,168 INFO     sending presence: <presence to="TheBrewery@conference.meet-07.talview.com" xml:lang="en"><jibri-status xmlns="http://jitsi.or
Mar 21 18:35:20 jibri jibri-xmpp[1949]: 2018-03-21 18:35:20,169 INFO     Started up client <jibrixmppclient.JibriXMPPClient object at 0x7fb21327def0>`

Followed the exact documentation of jibri and jitsi-meet  for whole setup

**Comment by cheelibrahmaiah** [comment]
JIBRI for now best supports for YouTube Streaming, if You need this feature follow given steps.
1. I found bellow line in your logs **roomname@conference.domain.com** is it right as per configuration please check it out.
2. Did you configure this:: **Prosody: create accounts for the two methods Jibri uses to connect** ?
3. Did you setup YouTube Stream Key properly?
4. Please verify **Connecting Jibri to Jitsi Meet** each and every point.

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian repository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
