### ISSUE TITLE
Multiple recording sessions with jibri.

### ISSUE THREAD

**Issue by ctscobra** [jitsi/jibri#70]
We have installed jibri and set recording to file.
Now we want to see how to add more jibri servers etc to have multiple parallel recordings.
How to add multiple servers to pool ?

**Comment by damencho** [comment]
You just need to install multiple jibri machines the same way, they all join a muc room which is monitored by jicofo and it chooses the next free one when recording is requested. But Aaron already mentioned all these in issue#33.
