### ISSUE TITLE
Display name is required .

### ISSUE THREAD

**Issue by ctscobra** [jitsi/jibri#73]
After updating jicofo ,jibri recording shows popup window "Display name required" .
On XMPP server jitsi meet config.js has following : 
    useNicks: false,
    requireDisplayName: false,

Values are not used anymore and the 'nick' is not used from jibri config.

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian repository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
