### ISSUE TITLE
Jibri keeps failing to start

### ISSUE THREAD

**Issue by nightstryke** [jitsi/jibri#77]
Here's my setup
Server B: Jitsi server with ip 192.168.1.2 (Not Actual IP just representative but accesssable via the web.)
Server A: Web Server that is pointing an A Record of hangout.mydomain.org to 192.168.1.2

Server A's hostname is set as hangout.mydomain.org

I have followed every install to the "Letter"

There is only one user account "jibri" as stated in the install instructions.

But jibri still will not broadcast to YouTube or my custom RTMP Server!

These are the errors I keep getting.

```
Apr 02 14:47:55 hangout app.py[3591]: 2018-04-02 14:47:55,715 INFO     Starting selenium attempt 1/3 pjsua_flag:False

Apr 02 14:47:55 hangout app.py[3591]: 2018-04-02 14:47:55,715 INFO     starting jibri selenium, url=https://hangout.mydomain.org/test#config.iAmRecorder=true&config.externalConnectUrl=null, google_account=None, xmpp_login=recorder@recorder.hangout.mydomain.org

Apr 02 14:48:25 hangout app.py[3591]: 2018-04-02 14:48:25,825 ERROR    Jibri Startup exception during attempt 1/3: Remote end closed connection without response

Apr 02 14:48:25 hangout app.py[3591]: 2018-04-02 14:48:25,829 INFO     start_jibri_selenium returned retcode=9999 during attempt 1/3

Apr 02 14:48:25 hangout app.py[3591]: 2018-04-02 14:48:25,831 INFO     Starting selenium attempt 2/3 pjsua_flag:False

Apr 02 14:48:25 hangout app.py[3591]: 2018-04-02 14:48:25,836 INFO     starting jibri selenium, url=https://hangout.mydomain.org/test#config.iAmRecorder=true&config.externalConnectUrl=null, google_account=None, xmpp_login=recorder@recorder.hangout.mydomain.org

Apr 02 14:48:55 hangout app.py[3591]: 2018-04-02 14:48:55,947 ERROR    Jibri Startup exception during attempt 2/3: Remote end closed connection without response

Apr 02 14:48:55 hangout app.py[3591]: 2018-04-02 14:48:55,949 INFO     start_jibri_selenium returned retcode=9999 during attempt 2/3

Apr 02 14:48:55 hangout app.py[3591]: 2018-04-02 14:48:55,949 INFO     Starting selenium attempt 3/3 pjsua_flag:False

Apr 02 14:48:55 hangout app.py[3591]: 2018-04-02 14:48:55,951 INFO     starting jibri selenium, url=https://hangout.mydomain.org/test#config.iAmRecorder=true&config.externalConnectUrl=null, google_account=None, xmpp_login=recorder@recorder.hangout.mydomain.org
```

I have tried the boshdomain fix, it does not work!

Please someone, anyone help!

**Comment by aaronkvanmeerten** [comment]
There's not enough details in the logs to be confident what's wrong, but it appears to be either chromedriver or chrome.  You can find the chrome logs in /tmp.  It may be that chrome isn't launching, or chromedriver is failing.  Did the manual test steps work correctly for you?

**Comment by nightstryke** [comment]
@aaronkvanmeerten Tell me what retcode=9999 means

**Comment by aaronkvanmeerten** [comment]
does the manual testing happen as the jibri user?
retcode 9999 means that selenium is either crashing or not responding.  So that's in line with what I said above, about it being an issue with communicating with chrome via selenium/chromedriver.

The fact that your jibriselenium.py call works is interesting.  Did you try it with a real conference URL (instead of just the root directory which serves the home page?)  Is there any output there to indicate that it's successfully connecting and able to check for download bitrate, etc?

**Comment by nightstryke** [comment]
Yes I have tried testing using this.
`DISPLAY=:0 ./jibriselenium.py -u https://hangout.mydomain.org/test`
And it succeeded, but when I try to go live via YouTube or my custom RTMP Server I receive the retcode=9999
