### ISSUE TITLE
New Jibri Install

### ISSUE THREAD

**Issue by nightstryke** [jitsi/jibri#83]
OK I'm lost with the new instructions and the new version.
I'm using ubuntu 16.04 and using the repository version of jist-meet.
I've followed the install pre-requisites, but it doesn't actually stipulate how to install the rest of jibri. What's the deal? @aaronkvanmeerten any ideas?

**Comment by fuqiangleon** [comment]
so do i ,did you get some new docs from  anywhere ?

**Comment by fuqiangleon** [comment]
its a bad news ,have you tried the python_jibri branch ?

**Comment by nightstryke** [comment]
Yeah that never worked.

**Comment by aaronkvanmeerten** [comment]
Using the jibri debian packages we have managed to deploy the jibri's running on meet.jit.si, so it's definitely possible.  The main things to note are:

You'll still need to have some of the pre-requisites installed and configure:

- alsa loopback in the kernel (snd-aloop in /etc/modules)
- ffmpeg of a reasonably recent version, the one in 16.04 xenial works fine for us
- java: we're using openjdk-8-jdk and openjdk-8-jre (8u151-b12-0ubuntu0.16.04.2 at last build)
- chrome and compatible chromedriver (we use the latest available when making a build.  The last build we made had google-chrome-stable 65.0.3325.181-1 with chromedriver 2.37.544315, but newer are available now and we've had no trouble moving along with whatever stable version is available at build time.)
- all the other components configured properly as in the README for prosody, jicofo, jitsi meet

We are presently using the debian packge of jibri with version 1.2.48-1, and I would recommend this latest one over any of the previous.  This jibri performs extremely quickly and seems not to suffer from many of the crashes and freezes that users here have reported.

If you're having problems installing or configuring Jibri please let us know the specifics of your issue.

**Comment by aaronkvanmeerten** [comment]
So I wrote all that and then realized we never put in the download instructions for actually installing the jibri package.  So perhaps that's the confusion.  I'm making a PR to fix that now.  Please let us know if there's any other blockers to use here, as we've tried to make the packages easier to consume than the previous python jibri.

**Comment by fuqiangleon** [comment]
@aaronkvanmeerten you mean jibri is  a deb package now ?where do we can find it ?

**Comment by fuqiangleon** [comment]
@aaronkvanmeerten 
another question , we have tried to install jibri in a docker container ,because we want to record  multiple  meeting same time ,but we can not start jibri-xorg service ,could you give me some help?

**Comment by fuqiangleon** [comment]
@aaronkvanmeerten  
i have found the deb package from jitsi/nightly build version and install it in ubuntu 16.04,but there are some errors : 
mv: cannot stat '/etc/jitsi/jibri/asoundrc': No such file or directory
mv: cannot stat '/etc/jitsi/jibri/icewm.preferences': No such file or directory

**Comment by aaronkvanmeerten** [comment]
It appears that may be due to some package versioning issues we had early on building this package.  I have begun to clean the repository and I hope to see it finished this morning.

Please confirm that you have Jibri package version jibri_1.2.48-1_all.deb
There may have been "later" versions release incorrectly which are possibly causing the problem you see.

**Comment by aaronkvanmeerten** [comment]
W.r.t docker, Jibri inside Docker has always had the potential to work as long as the snd-aloop kernel drivers can be mapped and loaded appropriately within the Docker container.
W.r.t running multiple recordings at once, our pattern here is to run multiple virtual machines, one per recording.  We run them in an autoscaling group which then allows a pool to be available at all times.  The challenge in running multiple recordings from the same machine are:

- An X server per recording must already be running.  The configuration files and service definitions will need to managed by hand
- An alsa loopback device per recording, with a custom asoundrc
- Configuration files for each jibri instance running on the machine

There's no specific reason one could not run this way, but the challenge is ensuring that one recording doesn't steal the resources for the others.

**Comment by aaronkvanmeerten** [comment]
We've fixed the repository to only have the latest stable jibri, as well as updating the README to reflect better installation instructions.  Thanks everybody on this tread who have commented.  Please open a new issue if you continue to have problems using the new jibri packages so we can track them there.
