### ISSUE TITLE
How can i  send the live stream to my stream server (like live555) with  python_jibri version

### ISSUE THREAD

**Issue by topgun97** [jitsi/jibri#91]

**Comment by bbaldino** [comment]
The python version of Jibri is no longer supported, so you'll need to move to the new version.

That being said, we don't currently support any live streaming services other than YouTube.

**Comment by bbaldino** [comment]
I'll add though that we are interested in supporting more streaming services (and perhaps even supporting a general 'rtmp' stream url), so PRs would be welcome (and @bgrozev has mentioned he may give this a shot at one point).
