### ISSUE TITLE
HeapDumpOnOutOfMemoryError

### ISSUE THREAD

**Issue by tes5884** [jitsi/jibri#94]
Streaming is barely working, and I'm seeing a ton of `java HeapDumpOnOutOfMemory` in htop.
The system has 2GB of RAM, in addition to a 2G swapfile. according to htop, only ~300M of memory is being used. 
Do I need to change the amount of memory available to Java? This is on the Jitsi side...

**Comment by aaronkvanmeerten** [comment]
The system is running X11 and Chrome as well as Java so you'll need to account for that.  For meet.jit.si we use the c5.xlarge VM type, which has 4 vCPUs and 8GB of RAM.  You may be able to make smaller-resolution recordings on a smaller instance size, but our current default configuration records at 720p, which may require more CPU or RAM than you've got assigned to it.

**Comment by tes5884** [comment]
For sure, the thing is it isn't using anything close to what I've got. Do I need to specify the max memory somewhere? This is issue is happening on Jitsi, not on Jicofo, so this might be the wrong place..

**Comment by bbaldino** [comment]
> This issue is happening on Jitsi, not on Jicofo, so this might be the wrong place..

What do you mean by "Jitsi" here?  Do you mean Jibri?

**Comment by tes5884** [comment]
Meaning the Jitsi server is showing those errors, not the Jibri server. I think I need to move this ticket to the Jitsi github page.

**Comment by bbaldino** [comment]
What is the "Jitsi Server" here?  The place where you're running Jicofo?

**Comment by tes5884** [comment]
Server that I'm running Jitsi and Jicofo on. Jibri is on a separate server.

**Comment by bbaldino** [comment]
Ok, just trying to understand because I think there's a vocab issue here...by "Jitsi" do you mean serving the jitsi-meet web code?

**Comment by tes5884** [comment]
Correct

**Comment by bbaldino** [comment]
I'd open this on Jicofo, but it does sound unexpected.  I dunno if we pass an explicit amount of memory to Jicofo when starting (I don't when launching from intellij and it works fine) and not sure what the defaults are, but it'd probably be worth playing with to see if it makes a difference.
