### ISSUE TITLE
Can't start recording (live stream) - Ffmpeg Errors

### ISSUE THREAD

**Issue by ultraboby** [jitsi/jibri#97]
This is from my jibri log:

SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.impl.AbstractFfmpegExecutor.error() Ffmpeg is running but doesn't appear to be encoding:
May  3 15:44:15 host119 launch.sh[909]: 2018-05-03 15:44:15.638 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.impl.AbstractFfmpegExecutor.error() Ffmpeg is running but doesn't appear to be encoding:
May  3 15:44:16 host119 launch.sh[909]: 2018-05-03 15:44:16.638 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.impl.AbstractFfmpegExecutor.error() Ffmpeg is running but doesn't appear to be encoding:
May  3 15:44:17 host119 launch.sh[909]: 2018-05-03 15:44:17.641 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.impl.AbstractFfmpegExecutor.error() Ffmpeg is running but doesn't appear to be encoding:
May  3 15:44:18 host119 launch.sh[909]: 2018-05-03 15:44:18.641 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.impl.AbstractFfmpegExecutor.error() Ffmpeg is running but doesn't appear to be encoding:   Duration: N/A, start: 1525351458.142652, bitrate: 1536 kb/s
May  3 15:44:19 host119 launch.sh[909]: 2018-05-03 15:44:19.644 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.impl.AbstractFfmpegExecutor.error() Ffmpeg exited with code 1.  Its most recent output was rtmp://a.rtmp.youtube.com/live2/jibri123: Unknown error occurred

**Comment by bbaldino** [comment]
It looks like the YouTube stream key you entered (`jibri123`) isn't a valid stream key.

**Comment by bbaldino** [comment]
But actually I think a bad stream key gives I/O error in Ffmpeg, so maybe you just obfuscated your actual stream key--which would be a good idea :).  I haven't seen 'unknown error occurred' before, but if you could attach the ffmpeg logs here we might get a better idea.

**Comment by ultraboby** [comment]
Yes, the stream key isn't valid that is the issue. Tnanks
