### ISSUE TITLE
Out of memory: Kill process  (chrome) 

### ISSUE THREAD

**Issue by ultraboby** [jitsi/jibri#98]
I have Vmware VM with 8GB RAM, and i see memory leak with chrome:

olated(file):0kB present:5242880kB managed:5110908kB mlocked:4kB dirty:12kB writeback:264kB mapped:31872kB shmem:4631472kB slab_reclaimable:22564kB slab_unreclaimable:15808kB kernel_stack:2560kB pagetables:9924kB unstable:0kB bounce:0kB free_pcp:120kB local_pcp:120kB free_cma:0kB writeback_tmp:0kB pages_scanned:75976 all_unreclaimable? yes
May  8 17:49:09 jibri kernel: [ 1981.614752] lowmem_reserve[]: 0 0 0 0 0
May  8 17:49:09 jibri kernel: [ 1981.614754] Node 0 DMA: 1*4kB (U) 1*8kB (U) 1*16kB (U) 1*32kB (U) 1*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15868kB
May  8 17:49:09 jibri kernel: [ 1981.614765] Node 0 DMA32: 146*4kB (UME) 77*8kB (UE) 94*16kB (UME) 61*32kB (UE) 27*64kB (UME) 9*128kB (UE) 4*256kB (UME) 1*512kB (U) 1*1024kB (U) 1*2048kB (M) 8*4096kB (UM) = 44912kB
May  8 17:49:09 jibri kernel: [ 1981.614775] Node 0 Normal: 243*4kB (UE) 121*8kB (UME) 162*16kB (UE) 59*32kB (E) 45*64kB (UME) 20*128kB (UME) 5*256kB (UE) 3*512kB (UE) 1*1024kB (U) 1*2048kB (U) 6*4096kB (UM) = 42324kB
May  8 17:49:09 jibri kernel: [ 1981.614786] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
May  8 17:49:09 jibri kernel: [ 1981.614788] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
May  8 17:49:09 jibri kernel: [ 1981.614789] 1852461 total pagecache pages
May  8 17:49:09 jibri kernel: [ 1981.614790] 420 pages in swap cache
May  8 17:49:09 jibri kernel: [ 1981.614792] Swap cache stats: add 728841, delete 728421, find 205784/235501
May  8 17:49:09 jibri kernel: [ 1981.614793] Free swap  = 0kB
May  8 17:49:09 jibri kernel: [ 1981.614794] Total swap = 520188kB
May  8 17:49:09 jibri kernel: [ 1981.614795] 2097038 pages RAM
May  8 17:49:09 jibri kernel: [ 1981.614796] 0 pages HighMem/MovableOnly
May  8 17:49:09 jibri kernel: [ 1981.614797] 53210 pages reserved
May  8 17:49:09 jibri kernel: [ 1981.614798] 0 pages cma reserved
May  8 17:49:09 jibri kernel: [ 1981.614798] 0 pages hwpoisoned
May  8 17:49:09 jibri kernel: [ 1981.614799] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
May  8 17:49:09 jibri kernel: [ 1981.614804] [  246]     0   246    10968     1125      23       3        0             0 systemd-journal
May  8 17:49:09 jibri kernel: [ 1981.614807] [  288]     0   288    25742       55      18       3        0             0 lvmetad
May  8 17:49:09 jibri kernel: [ 1981.614809] [  293]     0   293    11411      493      25       3        8         -1000 systemd-udevd
May  8 17:49:09 jibri kernel: [ 1981.614811] [  449]   109   449    25596       53      20       3        0             0 systemd-timesyn
May  8 17:49:09 jibri kernel: [ 1981.614814] [  546]     0   546     6511       48      18       3        0             0 atd
May  8 17:49:09 jibri kernel: [ 1981.614816] [  550]   102   550    10726      123      26       3        0          -900 dbus-daemon
May  8 17:49:09 jibri kernel: [ 1981.614818] [  603]   115   603    11292      179      27       3        0             0 avahi-daemon
May  8 17:49:09 jibri kernel: [ 1981.614820] [  607]     0   607     7136       81      18       3        0             0 systemd-logind
May  8 17:49:09 jibri kernel: [ 1981.614822] [  617]     0   617     7252       69      19       3        0             0 cron
May  8 17:49:09 jibri kernel: [ 1981.614824] [  622]     0   622     1099       21       8       3        0             0 acpid
May  8 17:49:09 jibri kernel: [ 1981.614826] [  624]     0   624    68942      175      36       3        0             0 accounts-daemon
May  8 17:49:09 jibri kernel: [ 1981.614828] [  630]     0   630     7469       54      19       3        0             0 cgmanager
May  8 17:49:09 jibri kernel: [ 1981.614831] [  632]   101   632    65673      229      30       3        0             0 rsyslogd
May  8 17:49:09 jibri kernel: [ 1981.614833] [  687]   115   687    11195       81      26       3        0             0 avahi-daemon
May  8 17:49:09 jibri kernel: [ 1981.614835] [  722]     0   722    69277      162      38       3        0             0 polkitd
May  8 17:49:09 jibri kernel: [ 1981.614837] [  818]     0   818     4032      218      11       3        0             0 dhclient
May  8 17:49:09 jibri kernel: [ 1981.614839] [  902]     0   902    16377      179      36       3        0         -1000 sshd
May  8 17:49:09 jibri kernel: [ 1981.614841] [  907]  1001   907   101717     5381     111       3        0             0 Xorg
May  8 17:49:09 jibri kernel: [ 1981.614843] [  913]     0   913     3984       33      13       3        0             0 agetty
May  8 17:49:09 jibri kernel: [ 1981.614845] [  922]   107   922   277454    30461     133       4       64             0 mysqld
May  8 17:49:09 jibri kernel: [ 1981.614848] [ 1020]     0  1020    24234      247      50       3        3             0 sshd
May  8 17:49:09 jibri kernel: [ 1981.614850] [ 1023]     0  1023     9207       70      21       3      122             0 systemd
May  8 17:49:09 jibri kernel: [ 1981.614852] [ 1029]     0  1029    15800      433      32       3       29             0 (sd-pam)
May  8 17:49:09 jibri kernel: [ 1981.614854] [ 1111]     0  1111     5690      302      17       3      208             0 bash
May  8 17:49:09 jibri kernel: [ 1981.614856] [ 1162]     0  1162    24234      233      50       3       12             0 sshd
May  8 17:49:09 jibri kernel: [ 1981.614858] [ 1201]     0  1201     5708      520      17       3       13             0 bash
May  8 17:49:09 jibri kernel: [ 1981.614860] [ 1220]  1001  1220    31336      558      37       4        0             0 chromedriver
May  8 17:49:09 jibri kernel: [ 1981.614863] [ 2833]  1001  2833     1668        8       8       3       11             0 icewm-session
May  8 17:49:09 jibri kernel: [ 1981.614865] [ 2839]  1001  2839    19232        9      43       3      145             0 icewmbg
May  8 17:49:09 jibri kernel: [ 1981.614867] [ 2840]  1001  2840    23288      187      48       3      301             0 icewm
May  8 17:49:09 jibri kernel: [ 1981.614869] [ 2846]  1001  2846    20030      137      41       3       29             0 icewmtray
May  8 17:49:09 jibri kernel: [ 1981.614871] [ 2848]  1001  2848  1006080    36500     146       6      319             0 java
May  8 17:49:09 jibri kernel: [ 1981.614873] [ 2860]     0  2860     6839      524      19       3        0             0 htop
May  8 17:49:09 jibri kernel: [ 1981.614875] [ 2888]     0  2888     1831       17       9       3        0             0 tail
May  8 17:49:09 jibri kernel: [ 1981.614877] [ 2892]  1001  2892    31336      684      39       4        0             0 chromedriver
May  8 17:49:09 jibri kernel: [ 1981.614879] [ 2905]  1001  2905   193305    14000     270       5        0             0 chrome
May  8 17:49:09 jibri kernel: [ 1981.614882] [ 2911]  1001  2911     1861       17      10       3        0             0 cat
May  8 17:49:09 jibri kernel: [ 1981.614884] [ 2912]  1001  2912     1861       17      10       3        0             0 cat
May  8 17:49:09 jibri kernel: [ 1981.614886] [ 2915]  1001  2915    99602     2277     158       5        0             0 chrome
May  8 17:49:09 jibri kernel: [ 1981.614888] [ 2916]  1001  2916     6430      136      17       4        0             0 nacl_helper
May  8 17:49:09 jibri kernel: [ 1981.614890] [ 2919]  1001  2919    99602     2278     124       5        0             0 chrome
May  8 17:49:09 jibri kernel: [ 1981.614892] [ 2963]  1001  2963   139230     5952     217       5        0           200 chrome
May  8 17:49:09 jibri kernel: [ 1981.614894] [ 3127]  1001  3127   125348     4047     149       5        0           200 chrome
May  8 17:49:09 jibri kernel: [ 1981.614896] [ 3176]  1001  3176   262985     3651     207      31        0           300 chrome
May  8 17:49:09 jibri kernel: [ 1981.614898] [ 3354]  1001  3354   351859    36445     450     153        0           300 chrome
May  8 17:49:09 jibri kernel: [ 1981.614900] [ 3384]  1001  3384  2124100     9574    1392       8        0             0 ffmpeg
May  8 17:49:09 jibri kernel: [ 1981.614902] Out of memory: Kill process 3354 (chrome) score 316 or sacrifice child

**Comment by bbaldino** [comment]
Hm, we haven't seen this issue on any of our deployments.  Unfortunately, we don't have any control over how much memory chrome uses...any chance maybe you've got an outdated chromedriver or chrome version?

**Comment by ultraboby** [comment]
ChromeDriver 2.38.552522

Package: google-chrome-stable
Version: 66.0.3359.139-1

**Comment by bbaldino** [comment]
Ok, so those are up to date.  I can only speculate at this point; from what I know this isn't a Jibri issue per se as much as something going on with chrome.  I'd just try normal debugging things:

Can you manually access the site with chrome ok?  Any memory issues there?

**Comment by ultraboby** [comment]
Hi, Is this normal behavior:

SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.impl.AbstractFfmpegExecutor.error() Ffmpeg is running but doesn't appear to be encoding:
May 10 13:55:38 jibri launch.sh[26583]: 2018-05-10 13:55:38.357 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.impl.AbstractFfmpegExecutor.error() Ffmpeg is running but doesn't appear to be encoding:
May 10 13:55:39 jibri launch.sh[26583]: 2018-05-10 13:55:39.360 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.impl.AbstractFfmpegExecutor.error() Ffmpeg is running but doesn't appear to be encoding:   Duration: N/A, start: 1525949739.044249, bitrate: 1536 kb/s

**Comment by bbaldino** [comment]
It is normal that, when first starting, ffmpeg takes a little while to 'get
going' and, until we see that it is actually encoding, we'll log lines like
that.

**Comment by ultraboby** [comment]
seems other peoples have the same issue with chrome on ubuntu 16.04:
https://productforums.google.com/forum/#!topic/chrome/pOFHOYVsIpI

**Comment by ultraboby** [comment]
very very very weird - after I changed the number of cpu cores from 1 to 2 the issue is disappear ?!
